// consoleCommandDocs.js — reference catalog for the system.chit_chat.how_do_i intent (Phase 1,
// 2026-08-10). "how do i X" questions used to fall through to the generic fallback because the
// matcher has no intent per feature; this catalog turns the question into a targeted answer:
// subject keywords are matched against COMMAND_DOCS entries (longest matching keyword wins) and
// up to three best entries are rendered by builtinChitChat.js's how_do_i handler.
//
// Entries mirror the README "Command reference" tables plus console features with no typed
// command (theme toggle, model picker, exports). `command` is the thing to type or the UI
// control to reach; `shell` (Phase 9, 2026-08-11) is the actual terminal command that thing
// runs, rendered as a code block next to the chat phrasing and offered as a clickable
// suggestion chip; `phrases` are alternate chat phrasings for the same action, shown so the
// user learns how to ask. Keywords are substrings of the question's subject ("check git
// status" contains "git status"), so keep them narrow — a keyword like "push" alone would
// hijack every "how do i push ..." question that belongs to git docs.
export const COMMAND_DOCS = [
  { keywords: ['run the site', 'run the project', 'run this project', 'launch the site', 'start the site', 'serve the site'], command: 'run the site', shell: 'npm run dev', phrases: ['run the site', 'start the server', 'serve the app'], explain: 'starts the project\'s dev server via its detected entry point and prints the link when it is up. The exact command depends on the project — npm run dev for Vite/React, python main.py serve for Flask, etc.' },
  { keywords: ['run the tests', 'run tests', 'test suite'], command: 'run the tests', shell: 'npm test', phrases: ['run the tests', 'run tests'], explain: 'finds and runs the project\'s test command (pytest, vitest, npm test, ...).' },
  { keywords: ['run the build', 'npm run', 'run the dev server', 'build the project'], command: 'run the build', shell: 'npm run build', phrases: ['run the build', 'build the project'], explain: 'matches package.json scripts — "run the build" runs the build script.' },
  { keywords: ['on port', 'specific port', 'different port', 'change the port'], command: 'run the site on port 3010', shell: 'npm run dev -- --port=3010', phrases: ['run the site on port 3010', 'serve the app on port 3040'], explain: 'starts the dev server on a specific port (replace 3010 with whatever you need); vite-shaped scripts use the --port flag, others get a PORT= env prefix.' },
  { keywords: ['stop the server', 'stop server', 'kill the server', 'stop it'], command: 'stop the server', phrases: ['stop the server', 'kill the server', 'stop it'], explain: 'stops the running dev server and anything else the console started for this project.' },
  { keywords: ['the link', 'url', 'site url'], command: 'what is the link', phrases: ['what is the link', 'where is the link', 'link?'], explain: 'prints the project\'s current dev-server URL (or that no server is responding).' },
  { keywords: ['push to github', 'push my changes', 'commit and push', 'push this', 'deploy', 'publish'], command: 'push to github', shell: 'git push', phrases: ['push to github', 'push my changes', 'deploy the site'], explain: 'checkpoint-commits all changes then pushes — deploy-on-push targets go live automatically.' },
  { keywords: ['commit my changes', 'commit with', 'commit the changes', 'commit'], command: 'commit "fix the login bug"', shell: 'git commit -m "message"', phrases: ['commit my changes', 'commit "fix the login bug"'], explain: 'commits without pushing — add your message in quotes.' },
  { keywords: ['git status', 'what changed', 'pending changes', 'working tree'], command: 'check git status', shell: 'git status --short', phrases: ['check git status', 'what changed', 'pending changes'], explain: 'shows uncommitted/unpushed changes.' },
  { keywords: ['git log', 'recent commits', 'commit history'], command: 'git log', shell: 'git log --oneline -10', phrases: ['git log', 'recent commits'], explain: 'shows recent commit history.' },
  { keywords: ['git diff', 'what did i change'], command: 'git diff', shell: 'git diff', phrases: ['git diff', 'what did i change'], explain: 'shows the diff of modified files.' },
  { keywords: ['checkpoint', 'backup my work', 'save my work'], command: 'make a checkpoint', shell: 'git add -A && git commit', phrases: ['make a checkpoint', 'checkpoint my work'], explain: 'git add-all plus a checkpoint commit before risky moves.' },
  { keywords: ['close a stale branch', 'prune branches', 'delete old branches'], command: 'clean up stale branches', shell: 'git branch --merged', phrases: ['clean up stale branches'], explain: 'lists merged branches you can safely delete.' },
  { keywords: ['export', 'pdf', 'markdown', 'chat log', 'download this conversation', 'json'], command: 'chat header download icon', explain: 'exports the current session as Markdown, JSON, or PDF from the chat header; the ⚙ session menu there additionally has "Export project chat log" (the full .console/chat-log.md).' },
  { keywords: ['schedule', 'scheduled', 'every 5 minutes', 'daily at', 'on file save', 'on git commit', 'timer'], command: 'schedule every 10 minutes "git status"', phrases: ['schedule every 10 minutes "git status"', 'schedule daily at 09:30 "run the tests"', 'schedule on file save "npm run lint"'], explain: 'runs a command on a timer or trigger; automated actions go through the normal confirm flow first.' },
  { keywords: ['list schedules', 'my schedules'], command: 'list schedules', phrases: ['list schedules', 'show my schedules'], explain: 'shows the project\'s scheduled/triggered commands.' },
  { keywords: ['delete schedule', 'remove schedule'], command: 'delete schedule 2', phrases: ['delete schedule 2', 'remove schedule 1'], explain: 'removes a scheduled command by its list number.' },
  { keywords: ['clipboard', 'copy history', 'snippet', 'copy snippet'], command: 'show clipboard history', phrases: ['show clipboard history', 'copy clipboard item 2', 'save this as a snippet: welcome', 'copy snippet welcome', 'clear clipboard history'], explain: 'shows/copies/clears recent OS clipboard entries and named snippets. Clipboard history polling is OPT-IN (Settings → Advanced → "Track clipboard history") — nothing reads your clipboard by default. The Clipboard panel (Tools > Clipboard, or type "open clipboard") shows both lists; all copies go through the server-side OS clipboard write so the CLI behaves identically.' },
  { keywords: ['csv', 'spreadsheet', 'sum column', 'average column', 'filter a csv', 'count rows'], command: 'sum column sales in data.csv', phrases: ['sum column sales in data.csv', 'average column price in data.csv', 'count rows in data.csv where status equals done', 'filter data.csv where price greater than 50'], explain: 'runs deterministic, read-only queries over a project CSV file (sum/average/count/filter; operators: equals/contains/greater than/less than). The Spreadsheet panel (Tools > Spreadsheet, or type "open spreadsheet") renders filter results as a sortable table.' },
  { keywords: ['auto-start', 'auto start', 'start automatically', 'start my project automatically', 'boot with'], command: 'auto-start this project', phrases: ['auto-start this project', 'auto-start netpulse', 'disable auto-start', 'run auto-start now'], explain: 'starts the project\'s dev server automatically at every console boot (skips when the site is already up); "run auto-start now" starts it immediately.' },
  { keywords: ['notify me', 'notifications', 'desktop alert', 'webhook', 'get notified', 'watch a folder', 'watched folders', 'file changes', 'stale folder'], command: 'notify me when files change in C:\\Users\\you\\Documents', phrases: ['notify me when files change in C:\\Users\\you\\Documents', 'notify me if C:\\Users\\you\\Downloads hasn\'t changed in 7 days', 'list watched folders', 'stop watching C:\\Users\\you\\Documents'], explain: 'file-watch notifications ("when files change in X, notify me") plus the dev-server/schedule/task events. Everything is OFF until you opt in per event; delivery is desktop toast and/or webhook. Watch rules are notification-only — they never run commands. The Notifications panel (Tools > Notifications, or type "open notifications") shows IFTTT-style rule cards.' },
  { keywords: ['theme', 'dark mode', 'light mode', 'accent color'], command: 'the theme toggle in the top bar (sun/moon)', explain: 'switches dark/light; the choice persists per browser.' },
  { keywords: ['model', 'ollama', 'cloud model', 'llama'], command: 'the model picker in the AI popover', explain: 'lists local Ollama and cloud models; pull new ones with the Ollama app (ollama pull llama3).' },
  { keywords: ['pack', 'custom tools', 'install a tool'], command: 'install pack <path-to-console.tools.json>', explain: 'adds custom tools from a local manifest — preview first, confirm to install.' },
  { keywords: ['pack registry', 'marketplace', 'browse packs', 'search packs'], command: 'browse pack registry', phrases: ['set pack registry https://example.com/registry.json', 'browse pack registry', 'search packs for deploy', 'install pack my-pack from registry'], explain: 'remote pack installation: set a registry URL (HTTPS, never defaulted — no silent network), browse/search its packs, and install with checksum verification through the same preview-then-confirm flow as local packs. This console does not host or vet any registry — you point it wherever you trust. The Pack Marketplace panel (Tools > Pack Marketplace) is an App Store-style grid.' },
  { keywords: ['learning', 'near miss', 'suggestions'], command: 'review learning', phrases: ['review learning', 'check learning'], explain: 'shows near-miss phrases the console learned from your corrections.' },
  { keywords: ['approve suggestions', 'promote suggestions'], command: 'approve suggestions 1 3', phrases: ['approve suggestions', 'approve suggestions 1 3'], explain: 'promotes selected learned phrases into intent examples.' },
  { keywords: ['telemetry', 'stats', 'threshold'], command: 'telemetry review', phrases: ['telemetry review', 'telemetry stats'], explain: 'shows intent match statistics and threshold tuning.' },
  { keywords: ['collisions'], command: 'check collisions', explain: 'finds intents that overlap in embedding space (cosine >= 0.9).' },
  { keywords: ['distillations', 'distillation'], command: 'review distillations', explain: 'shows AI-exchange observations distilled into trigger-style config suggestions.' },
  { keywords: ['review memory', 'memory patterns'], command: 'review memory', explain: 'shows the project\'s command/file/question usage patterns.' },
  { keywords: ['history', 'recent actions', 'revert action', 'undo an action'], command: 'show history', phrases: ['show history', 'recent actions', 'revert action 3f2a9c1d'], explain: 'lists the project\'s recent file edits and confirmed commands; "revert action <id>" restores a file edit or advises the git undo.' },
  { keywords: ['backup', 'zip', 'export this project', 'make a backup'], command: 'backup this folder', phrases: ['backup this folder', 'export this project as a zip', 'list backups'], explain: 'zips the project folder (or a named subfolder) to data/backups with a timestamp, returns the absolute path + a download link, and journals the zip so `revert action <id>` deletes it. Read-only against the source. The Backup panel (Tools > Backup, or type "open backup") lists past backups with download/show-in-folder.' },
  { keywords: ['health', 'healthy', 'self check'], command: 'health check', phrases: ['health check', 'is my console healthy'], explain: 'reports console health: Ollama reachability, embedding model state, free disk space, and zombie tracked processes.' },
  { keywords: ['match quality', 'match stats', 'matching quality', 'drift'], command: 'review match quality', phrases: ['review match quality', 'match quality'], explain: 'reads the rolling match-stats log (one line per trigger-mode message): per-intent mean/min confidence, stage distribution, and drift flags when an intent\'s recent mean dropped more than 0.1 vs the prior window — the signature of the phrase corpus growing over an intent. Read-only.' },
  { keywords: ['doctor', 'diagnose', 'diagnostic', 'ports', 'daemon'], command: 'console doctor', phrases: ['console doctor', 'run the doctor', 'diagnose the console'], explain: 'proactive machine-side checks: ports 3000-3019 free, daemon alive, embedding model cached, data/.cache writable, Ollama reachable, npm update status, tooling on PATH, disk space. Works without a running server via `npm run doctor` / `node bin/cli.js doctor` — the same checks the chat command runs.' },
  { keywords: ['search my documents', 'what did i write', 'my documents', 'search the pdfs', 'knowledge base'], command: 'search my documents for pricing', phrases: ['search my documents for pricing', 'what did i write about the budget', 'search the pdfs for the contract terms'], explain: 'searches the project\'s PDFs, Word docs and notes by meaning through an offline semantic index (same embedding model as the matcher, no cloud). Retrieval-only with real file citations; with AI mode on, a synthesized answer is added above the raw excerpts. The Documents panel (Tools > Documents, or type "open documents") shows the same results with index status.' },
  { keywords: ['coverage', 'test coverage'], command: 'what is my test coverage', phrases: ['what is my test coverage', 'how much coverage do we have'], explain: 'reads existing coverage artifacts (lcov.info / coverage-summary.json) — overall percentage plus the worst-covered files. Never runs anything.' },
  { keywords: ['bundle size', 'bundle analysis', 'large bundles'], command: 'analyze bundle size', phrases: ['analyze bundle size', 'how big is my bundle'], explain: 'walks existing build output (dist/build/out) and lists the largest assets with a total. Never runs a build.' },
  { keywords: ['switch projects', 'change projects', 'which project'], command: 'the project list in the left sidebar', explain: 'each project card opens a fresh chat session scoped to that project.' },
  { keywords: ['dashboard', 'live sites'], command: 'the Dashboard tab in the left sidebar', explain: 'project overview plus live-site status with per-project actions.' },
  { keywords: ['running processes', 'processes'], command: 'show running processes', explain: 'lists commands the console is tracking for this project.' },
  { keywords: ['vs code', 'vscode', 'cursor', 'explorer', 'terminal'], command: 'open the project in vs code', shell: 'code .', phrases: ['open in vs code', 'open this in visual studio code', 'open in cursor', 'open in explorer'], explain: 'opens the project folder in your editor/explorer/terminal.' },
  { keywords: ['github page'], command: 'open the github page', explain: 'opens the project\'s GitHub repo page in the browser.' },
  { keywords: ['create a file', 'new file', 'make a file'], command: 'create file notes.txt "hello"', phrases: ['create a file called notes.txt with the text "hello"'], explain: 'creates a file with quoted content (confirm-gated).' },
  { keywords: ['find the', 'find a file', 'locate', 'where is the file'], command: 'find the config file', phrases: ['find the config file', 'where is main.py'], explain: 'locates a file by name inside the project.' },
  { keywords: ['open html', 'open the html', 'preview the page', 'open in the browser', 'preview index', 'view the page', 'open the page', 'open in browser', 'open file in the browser'], command: 'open index.html in the browser', shell: 'start index.html', shellByPlatform: { darwin: 'open index.html', linux: 'xdg-open index.html' }, phrases: ['open index.html in the browser', 'preview the page', 'open the page in the browser', 'open report.pdf in the browser'], explain: 'opens a file in your default browser — HTML renders with all its assets (no dev server needed), other file types open/download per the OS association. Say "open <file> in vs code" (or just "open <file>") to open in the editor instead. The File Tools panel also has an in-console Preview button for HTML files.' },
  { keywords: ['open with', 'open in pycharm', 'open in intellij', 'open in the editor', 'choose editor', 'open in webstorm', 'default editor for'], command: 'open main.py with PyCharm', shell: 'pycharm64 main.py', shellByPlatform: { darwin: 'pycharm main.py', linux: 'pycharm main.py' }, phrases: ['open main.py with PyCharm', 'open app.ts in IntelliJ', 'open the config file in the editor'], explain: 'opens a file in the IDE you choose — "open X with <editor>" uses the configured editor, "open X in the editor" uses the per-extension default (Settings → Editors & IDEs, data/editors.json). Per-extension defaults ship for .py → PyCharm, .java → IntelliJ, .cpp/.ts/.c → VS Code, .html → browser, and so on — remap any of them in settings.' },
  { keywords: ['open in the folder', 'in explorer', 'reveal file', 'show file in explorer', 'show in file explorer'], command: 'open main.py in the folder', phrases: ['open main.py in the folder', 'show file.py in explorer', 'reveal main.py in file explorer'], explain: 'reveals the FILE in your OS file explorer (the folder opens with the file selected) — the file-level counterpart of "open the folder". Works for any file type.' },
  { keywords: ['browse a folder', 'browse any folder', 'folder explorer', 'file explorer', 'explore a folder', 'browse my files', 'see all files in a folder', 'view files as objects', 'grid view files', 'search a folder', 'open a file in its default app', 'search in a folder'], command: 'Tools → Folder Explorer', phrases: ['browse C:\\Users\\you\\Documents', 'how do i browse any folder', 'how do i search a folder', 'how do i open a file with its default app'], explain: 'the Folder Explorer panel (Tools grid, works in General mode with no project) browses ANY absolute path on disk. Paste the path, descend into subfolders (breadcrumb trail + back/forward/up buttons), and switch between Lines (list) and Objects (grid) views with the toggle at the bottom. The search bar filters the current folder\'s entries by name. Double-click (or Enter) on a file opens it in its OS default app via file association. Per-file actions: open in editor, open with a chosen IDE, open in browser (HTML), open in default app, or reveal in folder.' },
  { keywords: ['every folder', 'include all folders', 'all folders as projects', 'general mode shows everything', 'folders that arent projects'], command: 'Settings → "Include every folder as a project"', phrases: ['how do i see every folder', 'why is my folder missing'], explain: 'the scanAllFolders profile setting (Settings → Include every folder as a project): with it ON, every immediate subfolder of the scan root appears in the project list — even folders with no code/git/config (they classify as General). Off by default so junk folders stay hidden; turn it on, then rescan. Works per tab — each tab\'s scan respects the setting.' },
  { keywords: ['another tab', 'duplicate tab', 'second folder', 'scan another folder', 'two folders', 'multiple folders', 'tab for each project', 'project tabs', 'another scan folder', 'close a tab', 'close the tab', 'close tabs'], command: 'the tab strip at the top (New tab)', phrases: ['how do i scan another folder', 'can i have two folders open', 'how do i switch between folders', 'how do i close a tab'], explain: 'Chrome-style tabs: each tab owns its own scan folder, project list, and open chat. "New tab" duplicates the current tab so you can scan a different folder while the first keeps its own; every tab has an × to close it — closing the last one leaves a fresh default tab, so at least one always exists. Click a tab to switch — its projects and chat come back exactly as you left them. Tab layout persists across reloads.' },
  { keywords: ['chat history', 'my chats', 'old chats', 'previous conversations', 'chat list', 'open an old chat'], command: 'the Chats list in the left sidebar', phrases: ['where are my old chats', 'how do i open an old chat', 'my chat history is missing'], explain: 'every conversation is saved per project and listed in the sidebar (Chats section) — click any chat to reopen it; the console switches to the tab whose folder that project lives in, so the right project is active automatically. Chats are auto-titled from the first message; the pencil renames, the trash deletes.' },
  { keywords: ['find files', 'search for files', 'search files', 'duplicate files', 'remove duplicates', 'find duplicate'], command: 'find duplicate files', phrases: ['find duplicate files', 'delete duplicates, keep newest', 'search for X in my files'], explain: 'searches the project by filename and content, or finds/deletes duplicate files (read-only scan + confirm-gated cleanup). You can also open the File Tools panel (Tools > File Tools, or type "open file tools") for an interactive file browser and duplicate finder.' },
  { keywords: ['remember', 'memory.md', 'save a memory'], command: 'AI mode: "remember that ..."', explain: 'saves a durable cross-session fact to .console/memory.md (AI mode only).' },
  { keywords: ['a note', 'my notes', 'add a note', 'write a note'], command: 'note: buy milk', phrases: ['note: buy milk', 'add a note: ship the invoice', 'show my notes', 'search my notes for wifi'], explain: 'jots a user-authored scratch note to .console/notes.md (no confirmation), lists them most-recent-first, or searches them. You can also open the Notes panel (Tools > Notes, or type "open notes").' },
  { keywords: ['init', 'console.config.json', 'config file'], command: 'npx local-project-console init', shell: 'npx local-project-console init', phrases: ['run the initializer for this project'], explain: 'bootstraps a console.config.json for a project.' },
  { keywords: ['publish', 'npm publish', 'push to npm', 'publish to npm', 'publish this', 'release a new version', 'ship a new version', 'publish this app'], command: 'how do i publish this', shell: 'npm version patch && npm publish', phrases: ['how do i publish this', 'how do i publish a new version', 'how do i ship an update'], explain: 'publishes the app so other people can install it. First publish: `npm login`, then `npm version patch` (bump), then `npm publish`. Publish in one of THREE ways: (1) **npm registry** (recommended): `npm version patch && npm publish` — anyone then runs `npm install -g local-project-console`. (2) **Desktop installer**: `cd desktop && npm install && npm run dist` builds an NSIS `.exe` (Windows), `.dmg` (macOS) or `.AppImage` (Linux) that installs the app with no command line. (3) **Zip/binary**: copy the built `dist/` + `server/` folders or zip the repo. Before any publish run `npm run build` so `dist/` is up to date — npm ships whatever is on disk, not a fresh build. `package.json`\'s `"files"` array controls what ships (`bin/`, `dist/`, `server/`, README, LICENSE); gitignored files never publish.' },
  { keywords: ['install on another', 'install this on someone', 'run this on another machine', 'install on someone else', 'use it on someone else'], command: 'how do i install this on someone else\'s system', shell: 'npm install -g local-project-console', phrases: ['how do i install this on another computer', 'how do i set this up on someone else\'s laptop'], explain: 'once published, the person needs Node 18+. THREE ways: (1) **Global install**: `npm install -g local-project-console` then run `local-project-console` from any folder. (2) **No-install one-off**: `npx local-project-console` downloads and runs it without keeping a copy. (3) **Desktop installer**: if you shipped an `.exe`/`.dmg`, they just double-click it. Either way they get the same first-run wizard: pick or type a folder to scan. AI mode needs a local Ollama install (optional); everything else works with zero setup.' },
  { keywords: ['cli chat', 'cli mode', 'cli client', 'chat in the terminal', 'terminal chat'], command: 'npx local-project-console cli', shell: 'npx local-project-console cli', phrases: ['npx local-project-console cli'], explain: 'launches the console in CLI chat mode — the same interactive terminal agent start.bat\'s [C] option reaches. The server boots in the background, then the terminal becomes the chat: type commands, pick suggestions by number, and press Enter to send. Use the --dir / --project flags to target a specific folder. Exit with "exit" or Ctrl+C; the server stops with it. Installed users run `local-project-console cli` without the npx prefix.' },
  { keywords: ['build tools', 'visual studio', 'node-gyp', 'native module', 'gyp err', 'gyp error', 'c++ workload', 'desktop development'], command: 'how do i fix a native module build error', phrases: ['how do i fix the re2 build error', 'why does npm need visual studio', 'how do i fix node-gyp'], explain: 'this is the #1 install failure. Some dependencies (re2 for code search, sharp/onnxruntime for embeddings) are NATIVE modules — on Windows they compile with node-gyp, which needs Visual Studio with the "Desktop development with C++" workload, plus a Python build tool. If `npm install` ends with `gyp ERR! Could not find any Visual Studio installation`, either install that workload and retry, or — since re2 and the embedding package are now OPTIONAL — the console installs and runs fine WITHOUT them (matching falls back to fuzzy/NLP stages). Only the code-search and semantic-search features degrade. Do NOT use `--ignore-scripts` to force past the error — it silently breaks code search.' },
  { keywords: ['sharp', 'libvips', 'download timeout', 'sharp: Downloading', 'installation error'], command: 'how do i fix the sharp download timeout', phrases: ['why does sharp fail to install', 'how do i fix the sharp timeout'], explain: '`sharp` (a transitive dependency of the embedding package) downloads a native binary on install; on slow/restricted networks that download can time out. This is NOT a problem with the console — just retry `npm install` and it succeeds once the download completes. sharp is optional: if it never installs, the console still runs (embeddings fall back to fuzzy/NLP matching). To add it later run `npm i @xenova/transformers`.' },
  { keywords: ['eperm', 'cleanup failed', 'operation not permitted', 'access denied', 'rmdir', 'permission error'], command: 'how do i fix an eperm permission error', phrases: ['why does npm say eperm', 'how do i fix the cleanup error'], explain: '`npm error EPERM: operation not permitted, rmdir ...` on Windows usually means a file is locked — a running server/terminal, antivirus, or OneDrive holding a folder. Close any Node processes, retry, and if it persists run the install from an elevated (Administrator) PowerShell or clean the npm cache first (`npm cache clean --force`). A partial failed install leaves junk in `AppData\\Roaming\\npm\\node_modules` — delete that folder before reinstalling.' },
  { keywords: ['desktop app', 'electron', 'installer', 'exe', 'dmg', 'appimage', 'desktop version', 'rebuild the desktop app', 'release an update', 'release the desktop app', 'desktop release', 'github release', 'release pipeline', 'trigger the build', 'desktop auto update', 'auto update', 'update the desktop app', 'run the build', 'build the app', 'build this app', 'build the console', 'app icon', 'change icon', 'update icon', 'change my app icon', 'replace icon'], command: 'how do i build the desktop app', shell: 'cd desktop && npm install && npm run dist', phrases: ['how do i build the desktop installer', 'how do i make an exe', 'how do i rebuild the desktop app', 'how do i release an update', 'how do i trigger the desktop build', 'how do i change my app icon'], explain: 'the console also ships as a self-contained desktop app (Electron wrapper in `desktop/`, its own package.json so the root install never pulls Electron). `cd desktop && npm install && npm run dist` builds the Windows NSIS installer; the full step-by-step build + release pipeline (staging script, electron-builder, CI trigger, GitHub Release, auto-update) is maintained in server/desktop-release.md and rendered in full below.', doc: 'desktop-release.md' },
  { keywords: ['help', 'commands', 'what can you do', 'use a command', 'use commands', 'use the commands'], command: 'help', phrases: ['help', 'what can you do', 'how do i use a command'], explain: 'prints the full command reference.' },
  { keywords: ['list commands', 'help all', 'all commands'], command: 'list commands', phrases: ['list commands', 'help all', 'show all commands'], explain: 'prints the ENTIRE command catalog (every entry, phrase → shell command) as plain text — the CLI\'s equivalent of the Command Reference tab (the book icon in the header).' },
  { keywords: ['a reminder', 'reminders', 'remind me', 'set a reminder'], command: 'remind me tomorrow at 9am to renew my license', phrases: ['remind me in 3 days to follow up', 'list my reminders', 'cancel reminder s2'], explain: 'creates/lists/cancels personal reminders with free-form natural-language dates. Fires to the open chat (or schedule log when nobody is connected). You can also open the Reminders panel (Tools > Reminders, or type "open reminders").' },
  { keywords: ['what port', 'port number', 'port are you'], command: 'what port are you running on', explain: 'tells you the console\'s own port.' },
  { keywords: ['convert', 'km to miles', 'units', 'unit conversion', 'tip on', 'tax to', 'percent of', 'percentage'], command: 'convert 5 km to miles', phrases: ['convert 5 km to miles', 'how many cups in 2 liters', 'what is 15% of 80', 'whats 18% tip on 64.50', 'add 8.25% tax to 120'], explain: 'converts between units (length/weight/volume/temperature, offline) and does percentage/tip/tax math through the same safe evaluator as basic arithmetic. The Calculator panel (Tools > Calculator, or type "open calculator") has the same functions as a live widget.' },
  { keywords: ['undo', 'revert that', 'made a mistake'], command: 'undo', explain: 'restores the last change (git checkpoint or file journal).' },
  { keywords: ['run a command', 'execute a command', 'type a command'], command: 'type the command directly', explain: 'allowlisted command lines (git push, npm run ...) run as-is without the matcher.' },
  // Round-6 audit (2026-08-24): repo-map panel — the visual counterpart of the whole-project
  // symbol map the AI system prompt receives. Keywords stay on the "repo map" noun so
  // structure-shaped questions ("how do i see the project structure") keep their own routes.
  { keywords: ['repo map', 'symbol map', 'see what a file exports'], command: 'open repo map', phrases: ['open repo map', 'show the repo map'], explain: 'opens the Repo Map panel (Tools > Repo Map): every indexed code file with its top-level exports/functions/classes, imports, and reverse "used by" list, plus the detected API routes — the same structure the AI prompt is built from, made visible. Read-only; the map is the project\'s cached codebase index.' },
  { keywords: ['version', 'what version', 'which version', 'current version', 'app version'], command: 'check for updates', phrases: ['check for updates', 'what version am i running'], explain: 'shows the console version (package.json) and whether an npm update is available. Type "check for updates" to probe the registry; "update console" installs the latest version with confirmation. In the desktop app, updates are handled by the built-in auto-updater (Tools > Pack Marketplace does not apply here).' },
  { keywords: ['offline', 'is this offline', 'online', 'internet required', 'needs internet'], command: 'offline status', phrases: ['is this offline', 'does this need internet'], explain: 'the console is fully offline by design — no cloud calls in trigger mode. The only online features are Ollama cloud models (optional, via your local Ollama), web search (AI mode only, when you ask it to search), and "check for updates" (explicit registry fetch). Everything else — matcher, file tools, CSV/PDF, notes, indexing — runs locally on your machine.' },
  { keywords: ['ai mode', 'trigger mode', 'ai vs trigger', 'difference between ai and trigger', 'what is ai mode'], command: 'AI mode vs trigger mode', phrases: ['what is ai mode vs trigger mode', 'how is this different from terminal'], explain: 'trigger mode (default) matches your text against ~149 fixed intents locally — no model, no network, deterministic. AI mode (toggle in the chat header) hands the conversation to your local Ollama model with tools scoped to this project\'s folder — open-ended fixes, explanations, and multi-step tasks. Type "how do i set up ai mode" for the Ollama setup.' },
  { keywords: ['data safe', 'where does my data', 'where is my data stored', 'privacy', 'is my data private', 'data storage'], command: 'where does my data get stored', phrases: ['is my data safe', 'where does my data get stored'], explain: 'everything stays on your machine: projects are your folders, sessions and action history live in each project\'s .console/ folder, global state (telemetry, schedules, clipboard/snippets) in data/ at the console root. Nothing is sent to a cloud unless you explicitly use Ollama cloud models or AI-mode web search. The server binds to 127.0.0.1 by default (use HOST=0.0.0.0 only on a trusted LAN — it executes shell commands with no auth).' },
  { keywords: ['settings', 'preferences', 'user profile', 'accent color', 'sandbox mode', 'permission mode'], command: 'open settings (User Profile)', phrases: ['how do i get to settings', 'how do i change accent color', 'turn on sandbox mode'], explain: 'settings live in the User Profile modal (gear icon in the header): accent color, theme, locale, clipboard history opt-in, sandbox risky commands, permission mode, default workspace type, and the tuning knobs. Type "turn on sandbox mode" or "change accent color to blue" to change them via chat as well — chat settings commands persist to data/user-profile.json.' },
  { keywords: ['history', 'recent actions', 'what happened earlier', 'see history', 'action history'], command: 'show history', phrases: ['show history', 'recent actions', 'how do i see what happened earlier'], explain: 'the History tab (in the process dock) lists the last ~200 actions — file edits, confirmed commands, and notes — with "revert action <id>" to undo a file edit. Type "show history" or "recent actions" in chat for the same list.' },
  { keywords: ['terminal view', 'open in terminal', 'open terminal', 'command prompt'], command: 'open the project in terminal', phrases: ['open in terminal', 'open command prompt', 'how do i open terminal view'], explain: 'opens the project folder in your system terminal (Terminal app on macOS, cmd/PowerShell on Windows, your default on Linux) — same as "open the project in terminal" from chat.' },
];

/**
 * Best COMMAND_DOCS entries for a "how do I ..." question. Strips the how-do-i prefix, matches
 * keywords as substrings of the remaining subject, and returns up to three entries ordered by
 * longest matching keyword (more specific wins). Empty subject or no hits -> [].
 */
export function lookupCommandDocs(input) {
  const subject = input
    .replace(/^how\s+(?:do|can|would|does|did|should|could|to)\s+(?:i|we|you|me)?\s*/i, '')
    // "what('s| is) the best/easiest way to X" is the same HOW question with a longer prefix
    // (2026-08-26 crosscheck: it misfired onto deploy — the prefix must strip to the subject).
    .replace(/^what(?:'s|s| is) the (?:best|easiest) way to\s*/i, '')
    .replace(/[?!.\s]+$/g, '')
    .toLowerCase();
  if (!subject) return [];
  const scored = [];
  for (const entry of COMMAND_DOCS) {
    let best = 0;
    for (const keyword of entry.keywords) {
      if (subject.includes(keyword) && keyword.length > best) best = keyword.length;
    }
    if (best > 0) scored.push({ entry, best });
  }
  scored.sort((a, b) => b.best - a.best);
  return scored.slice(0, 3).map((s) => s.entry);
}

/**
 * The shell command for a catalog entry on THIS server's platform (2026-08-24): entries whose
 * example shell is Windows-flavored (`start index.html`, `pycharm64 ...`) carry an additive
 * `shellByPlatform` map; anything else falls back to the flat `shell`. The server's platform is
 * authoritative — the CLI and the web Command Reference run against this machine.
 */
export function resolveShell(entry) {
  if (!entry) return null;
  const byPlatform = entry.shellByPlatform;
  if (byPlatform && byPlatform[process.platform]) return byPlatform[process.platform];
  return entry.shell || null;
}