// consoleCommandDocs.js — reference catalog for the system.chit_chat.how_do_i intent (Phase 1,
// 2026-08-10). "how do i X" questions used to fall through to the generic fallback because the
// matcher has no intent per feature; this catalog turns the question into a targeted answer:
// subject keywords are matched against COMMAND_DOCS entries (longest matching keyword wins) and
// up to three best entries are rendered by builtinChitChat.js's how_do_i handler.
//
// Entries mirror the README "Command reference" tables plus console features with no typed
// command (theme toggle, model picker, exports). `command` is the thing to type or the UI
// control to reach; `shell` (Phase 9, 2026-08-11) is the actual terminal command that thing
// runs, rendered as a code block next to the chat phrasing and offered as a clickable
// suggestion chip; `phrases` are alternate chat phrasings for the same action, shown so the
// user learns how to ask. Keywords are substrings of the question's subject ("check git
// status" contains "git status"), so keep them narrow — a keyword like "push" alone would
// hijack every "how do i push ..." question that belongs to git docs.
export const COMMAND_DOCS = [
  { keywords: ['run the site', 'run the project', 'run this project', 'launch the site', 'start the site', 'serve the site'], command: 'run the site', shell: 'npm run dev', phrases: ['run the site', 'start the server', 'serve the app'], explain: 'starts the project\'s dev server via its detected entry point and prints the link when it is up. The exact command depends on the project — npm run dev for Vite/React, python main.py serve for Flask, etc.' },
  { keywords: ['run the tests', 'run tests', 'test suite'], command: 'run the tests', shell: 'npm test', phrases: ['run the tests', 'run tests'], explain: 'finds and runs the project\'s test command (pytest, vitest, npm test, ...).' },
  { keywords: ['run the build', 'npm run', 'run the dev server', 'build the project'], command: 'run the build', shell: 'npm run build', phrases: ['run the build', 'build the project'], explain: 'matches package.json scripts — "run the build" runs the build script.' },
  { keywords: ['on port', 'specific port', 'different port', 'change the port'], command: 'run the site on port 3010', shell: 'npm run dev -- --port=3010', phrases: ['run the site on port 3010', 'serve the app on port 3040'], explain: 'starts the dev server on a specific port (replace 3010 with whatever you need); vite-shaped scripts use the --port flag, others get a PORT= env prefix.' },
  { keywords: ['stop the server', 'stop server', 'kill the server', 'stop it'], command: 'stop the server', phrases: ['stop the server', 'kill the server', 'stop it'], explain: 'stops the running dev server and anything else the console started for this project.' },
  { keywords: ['the link', 'url', 'site url'], command: 'what is the link', phrases: ['what is the link', 'where is the link', 'link?'], explain: 'prints the project\'s current dev-server URL (or that no server is responding).' },
  { keywords: ['push to github', 'push my changes', 'commit and push', 'push this', 'deploy'], command: 'push to github', shell: 'git push', phrases: ['push to github', 'push my changes', 'deploy the site'], explain: 'checkpoint-commits all changes then pushes — deploy-on-push targets go live automatically.' },
  { keywords: ['commit my changes', 'commit with', 'commit the changes'], command: 'commit "fix the login bug"', shell: 'git commit -m "message"', phrases: ['commit my changes', 'commit "fix the login bug"'], explain: 'commits without pushing — add your message in quotes.' },
  { keywords: ['git status', 'what changed', 'pending changes', 'working tree'], command: 'check git status', shell: 'git status --short', phrases: ['check git status', 'what changed', 'pending changes'], explain: 'shows uncommitted/unpushed changes.' },
  { keywords: ['git log', 'recent commits', 'commit history'], command: 'git log', shell: 'git log --oneline -10', phrases: ['git log', 'recent commits'], explain: 'shows recent commit history.' },
  { keywords: ['git diff', 'what did i change'], command: 'git diff', shell: 'git diff', phrases: ['git diff', 'what did i change'], explain: 'shows the diff of modified files.' },
  { keywords: ['checkpoint', 'backup my work', 'save my work'], command: 'make a checkpoint', shell: 'git add -A && git commit', phrases: ['make a checkpoint', 'checkpoint my work'], explain: 'git add-all plus a checkpoint commit before risky moves.' },
  { keywords: ['close a stale branch', 'prune branches', 'delete old branches'], command: 'clean up stale branches', shell: 'git branch --merged', phrases: ['clean up stale branches'], explain: 'lists merged branches you can safely delete.' },
  { keywords: ['export', 'pdf', 'markdown', 'chat log', 'download this conversation', 'json'], command: 'chat header download icon', explain: 'exports the current session as Markdown, JSON, or PDF; the project chat log downloads from the session list.' },
  { keywords: ['schedule', 'scheduled', 'every 5 minutes', 'daily at', 'on file save', 'on git commit', 'timer'], command: 'schedule every 10 minutes "git status"', phrases: ['schedule every 10 minutes "git status"', 'schedule daily at 09:30 "run the tests"', 'schedule on file save "npm run lint"'], explain: 'runs a command on a timer or trigger; automated actions go through the normal confirm flow first.' },
  { keywords: ['list schedules', 'my schedules'], command: 'list schedules', phrases: ['list schedules', 'show my schedules'], explain: 'shows the project\'s scheduled/triggered commands.' },
  { keywords: ['delete schedule', 'remove schedule'], command: 'delete schedule 2', phrases: ['delete schedule 2', 'remove schedule 1'], explain: 'removes a scheduled command by its list number.' },
  { keywords: ['clipboard', 'copy history', 'snippet', 'copy snippet'], command: 'show clipboard history', phrases: ['show clipboard history', 'copy clipboard item 2', 'save this as a snippet: welcome', 'copy snippet welcome', 'clear clipboard history'], explain: 'shows/copies/clears recent OS clipboard entries and named snippets. Clipboard history polling is OPT-IN (Settings → Advanced → "Track clipboard history") — nothing reads your clipboard by default. The Clipboard panel (Tools > Clipboard, or type "open clipboard") shows both lists; all copies go through the server-side OS clipboard write so the CLI behaves identically.' },
  { keywords: ['csv', 'spreadsheet', 'sum column', 'average column', 'filter a csv', 'count rows'], command: 'sum column sales in data.csv', phrases: ['sum column sales in data.csv', 'average column price in data.csv', 'count rows in data.csv where status equals done', 'filter data.csv where price greater than 50'], explain: 'runs deterministic, read-only queries over a project CSV file (sum/average/count/filter; operators: equals/contains/greater than/less than). The Spreadsheet panel (Tools > Spreadsheet, or type "open spreadsheet") renders filter results as a sortable table.' },
  { keywords: ['auto-start', 'auto start', 'start automatically', 'start my project automatically', 'boot with'], command: 'auto-start this project', phrases: ['auto-start this project', 'auto-start netpulse', 'disable auto-start', 'run auto-start now'], explain: 'starts the project\'s dev server automatically at every console boot (skips when the site is already up); "run auto-start now" starts it immediately.' },
  { keywords: ['notify me', 'notifications', 'desktop alert', 'webhook', 'get notified', 'watch a folder', 'watched folders', 'file changes', 'stale folder'], command: 'notify me when files change in C:\\Users\\you\\Documents', phrases: ['notify me when files change in C:\\Users\\you\\Documents', 'notify me if C:\\Users\\you\\Downloads hasn\'t changed in 7 days', 'list watched folders', 'stop watching C:\\Users\\you\\Documents'], explain: 'file-watch notifications ("when files change in X, notify me") plus the dev-server/schedule/task events. Everything is OFF until you opt in per event; delivery is desktop toast and/or webhook. Watch rules are notification-only — they never run commands. The Notifications panel (Tools > Notifications, or type "open notifications") shows IFTTT-style rule cards.' },
  { keywords: ['theme', 'dark mode', 'light mode'], command: 'the theme toggle in the top bar (sun/moon)', explain: 'switches dark/light; the choice persists per browser.' },
  { keywords: ['model', 'ollama', 'cloud model', 'llama'], command: 'the model picker in the AI popover', explain: 'lists local Ollama and cloud models; pull new ones with the Ollama app (ollama pull llama3).' },
  { keywords: ['pack', 'custom tools', 'install a tool'], command: 'install pack <path-to-console.tools.json>', explain: 'adds custom tools from a local manifest — preview first, confirm to install.' },
  { keywords: ['pack registry', 'marketplace', 'browse packs', 'search packs'], command: 'browse pack registry', phrases: ['set pack registry https://example.com/registry.json', 'browse pack registry', 'search packs for deploy', 'install pack my-pack from registry'], explain: 'remote pack installation: set a registry URL (HTTPS, never defaulted — no silent network), browse/search its packs, and install with checksum verification through the same preview-then-confirm flow as local packs. This console does not host or vet any registry — you point it wherever you trust. The Pack Marketplace panel (Tools > Pack Marketplace) is an App Store-style grid.' },
  { keywords: ['learning', 'near miss', 'suggestions'], command: 'review learning', phrases: ['review learning', 'check learning'], explain: 'shows near-miss phrases the console learned from your corrections.' },
  { keywords: ['approve suggestions', 'promote suggestions'], command: 'approve suggestions 1 3', phrases: ['approve suggestions', 'approve suggestions 1 3'], explain: 'promotes selected learned phrases into intent examples.' },
  { keywords: ['telemetry', 'stats', 'threshold'], command: 'telemetry review', phrases: ['telemetry review', 'telemetry stats'], explain: 'shows intent match statistics and threshold tuning.' },
  { keywords: ['collisions'], command: 'check collisions', explain: 'finds intents that overlap in embedding space (cosine >= 0.9).' },
  { keywords: ['distillations', 'distillation'], command: 'review distillations', explain: 'shows AI-exchange observations distilled into trigger-style config suggestions.' },
  { keywords: ['review memory', 'memory patterns'], command: 'review memory', explain: 'shows the project\'s command/file/question usage patterns.' },
  { keywords: ['history', 'recent actions', 'revert action', 'undo an action'], command: 'show history', phrases: ['show history', 'recent actions', 'revert action 3f2a9c1d'], explain: 'lists the project\'s recent file edits and confirmed commands; "revert action <id>" restores a file edit or advises the git undo.' },
  { keywords: ['backup', 'zip', 'export this project', 'make a backup'], command: 'backup this folder', phrases: ['backup this folder', 'export this project as a zip', 'list backups'], explain: 'zips the project folder (or a named subfolder) to data/backups with a timestamp, returns the absolute path + a download link, and journals the zip so `revert action <id>` deletes it. Read-only against the source. The Backup panel (Tools > Backup, or type "open backup") lists past backups with download/show-in-folder.' },
  { keywords: ['health', 'healthy', 'self check'], command: 'health check', phrases: ['health check', 'is my console healthy'], explain: 'reports console health: Ollama reachability, embedding model state, free disk space, and zombie tracked processes.' },
  { keywords: ['search my documents', 'what did i write', 'my documents', 'search the pdfs', 'knowledge base'], command: 'search my documents for pricing', phrases: ['search my documents for pricing', 'what did i write about the budget', 'search the pdfs for the contract terms'], explain: 'searches the project\'s PDFs, Word docs and notes by meaning through an offline semantic index (same embedding model as the matcher, no cloud). Retrieval-only with real file citations; with AI mode on, a synthesized answer is added above the raw excerpts. The Documents panel (Tools > Documents, or type "open documents") shows the same results with index status.' },
  { keywords: ['coverage', 'test coverage'], command: 'what is my test coverage', phrases: ['what is my test coverage', 'how much coverage do we have'], explain: 'reads existing coverage artifacts (lcov.info / coverage-summary.json) — overall percentage plus the worst-covered files. Never runs anything.' },
  { keywords: ['bundle size', 'bundle analysis', 'large bundles'], command: 'analyze bundle size', phrases: ['analyze bundle size', 'how big is my bundle'], explain: 'walks existing build output (dist/build/out) and lists the largest assets with a total. Never runs a build.' },
  { keywords: ['switch projects', 'change projects', 'which project'], command: 'the project list in the left sidebar', explain: 'each project card opens a fresh chat session scoped to that project.' },
  { keywords: ['dashboard', 'live sites'], command: 'the Dashboard tab in the left sidebar', explain: 'project overview plus live-site status with per-project actions.' },
  { keywords: ['running processes', 'processes'], command: 'show running processes', explain: 'lists commands the console is tracking for this project.' },
  { keywords: ['vs code', 'vscode', 'cursor', 'explorer', 'terminal'], command: 'open the project in vs code', shell: 'code .', phrases: ['open in vs code', 'open this in visual studio code', 'open in cursor', 'open in explorer'], explain: 'opens the project folder in your editor/explorer/terminal.' },
  { keywords: ['github page'], command: 'open the github page', explain: 'opens the project\'s GitHub repo page in the browser.' },
  { keywords: ['create a file', 'new file', 'make a file'], command: 'create file notes.txt "hello"', phrases: ['create a file called notes.txt with the text "hello"'], explain: 'creates a file with quoted content (confirm-gated).' },
  { keywords: ['find the', 'find a file', 'locate', 'where is the file'], command: 'find the config file', phrases: ['find the config file', 'where is main.py'], explain: 'locates a file by name inside the project.' },
  { keywords: ['find files', 'search for files', 'search files', 'duplicate files', 'remove duplicates', 'find duplicate'], command: 'find duplicate files', phrases: ['find duplicate files', 'delete duplicates, keep newest', 'search for X in my files'], explain: 'searches the project by filename and content, or finds/deletes duplicate files (read-only scan + confirm-gated cleanup). You can also open the File Tools panel (Tools > File Tools, or type "open file tools") for an interactive file browser and duplicate finder.' },
  { keywords: ['remember', 'memory.md', 'save a memory'], command: 'AI mode: "remember that ..."', explain: 'saves a durable cross-session fact to .console/memory.md (AI mode only).' },
  { keywords: ['a note', 'my notes', 'add a note', 'write a note'], command: 'note: buy milk', phrases: ['note: buy milk', 'add a note: ship the invoice', 'show my notes', 'search my notes for wifi'], explain: 'jots a user-authored scratch note to .console/notes.md (no confirmation), lists them most-recent-first, or searches them. You can also open the Notes panel (Tools > Notes, or type "open notes").' },
  { keywords: ['init', 'console.config.json', 'config file'], command: 'npx local-project-console init', shell: 'npx local-project-console init', phrases: ['run the initializer for this project'], explain: 'bootstraps a console.config.json for a project.' },
  { keywords: ['publish', 'npm publish', 'push to npm', 'release a new version', 'ship a new version'], command: 'how do i publish this', shell: 'npm version patch && npm publish', phrases: ['how do i publish this', 'how do i publish a new version', 'how do i ship an update'], explain: 'bumps the version in package.json (patch/minor/major) then publishes to the npm registry — requires `npm login` once beforehand. See the README\'s "Publishing & installing on another machine" section for the full walkthrough.' },
  { keywords: ['install on another', 'install this on someone', 'run this on another machine', 'install on someone else', 'use it on someone else'], command: 'how do i install this on someone else\'s system', shell: 'npm install -g local-project-console', phrases: ['how do i install this on another computer', 'how do i set this up on someone else\'s laptop'], explain: 'once published, anyone can run `npm install -g local-project-console` (or `npx local-project-console` for a one-off, no-install run) and then just `local-project-console` from any folder — no need to clone this repo.' },
  { keywords: ['help', 'commands', 'what can you do'], command: 'help', phrases: ['help', 'what can you do'], explain: 'prints the full command reference.' },
  { keywords: ['list commands', 'help all', 'all commands'], command: 'list commands', phrases: ['list commands', 'help all', 'show all commands'], explain: 'prints the ENTIRE command catalog (every entry, phrase → shell command) as plain text — the CLI\'s equivalent of the Command Reference tab (the book icon in the header).' },
  { keywords: ['a reminder', 'reminders', 'remind me', 'set a reminder'], command: 'remind me tomorrow at 9am to renew my license', phrases: ['remind me in 3 days to follow up', 'list my reminders', 'cancel reminder s2'], explain: 'creates/lists/cancels personal reminders with free-form natural-language dates. Fires to the open chat (or schedule log when nobody is connected). You can also open the Reminders panel (Tools > Reminders, or type "open reminders").' },
  { keywords: ['what port', 'port number', 'port are you'], command: 'what port are you running on', explain: 'tells you the console\'s own port.' },
  { keywords: ['convert', 'km to miles', 'units', 'unit conversion', 'tip on', 'tax to', 'percent of', 'percentage'], command: 'convert 5 km to miles', phrases: ['convert 5 km to miles', 'how many cups in 2 liters', 'what is 15% of 80', 'whats 18% tip on 64.50', 'add 8.25% tax to 120'], explain: 'converts between units (length/weight/volume/temperature, offline) and does percentage/tip/tax math through the same safe evaluator as basic arithmetic. The Calculator panel (Tools > Calculator, or type "open calculator") has the same functions as a live widget.' },
  { keywords: ['undo', 'revert that', 'made a mistake'], command: 'undo', explain: 'restores the last change (git checkpoint or file journal).' },
  { keywords: ['run a command', 'execute a command', 'type a command'], command: 'type the command directly', explain: 'allowlisted command lines (git push, npm run ...) run as-is without the matcher.' },
];

/**
 * Best COMMAND_DOCS entries for a "how do I ..." question. Strips the how-do-i prefix, matches
 * keywords as substrings of the remaining subject, and returns up to three entries ordered by
 * longest matching keyword (more specific wins). Empty subject or no hits -> [].
 */
export function lookupCommandDocs(input) {
  const subject = input
    .replace(/^how\s+(?:do|can|would|does|did|should|could|to)\s+(?:i|we|you|me)?\s*/i, '')
    .replace(/[?!.\s]+$/g, '')
    .toLowerCase();
  if (!subject) return [];
  const scored = [];
  for (const entry of COMMAND_DOCS) {
    let best = 0;
    for (const keyword of entry.keywords) {
      if (subject.includes(keyword) && keyword.length > best) best = keyword.length;
    }
    if (best > 0) scored.push({ entry, best });
  }
  scored.sort((a, b) => b.best - a.best);
  return scored.slice(0, 3).map((s) => s.entry);
}