export const INTENTS = {
  'system.chit_chat.greeting': {
    examples: [
      'hi', 'hello', 'hey', 'yo', 'good morning', 'good evening',
      'good afternoon', 'greetings', 'hey there', 'hi there', 'howdy', 'sup',
      'whats up', 'howdy partner', 'ello', 'hiya', 'hey hey', 'morning',
      'evening', 'how are you today', 'hello there', 'hi, how are you',
      'ey up', 'wassup', 'whats good', 'yo yo', 'greetings and salutations',
      'hey what is up', 'hello friend', 'hi there buddy', 'hello world',
      'helloo', 'hellooo', 'heyy', 'hiiii', 'hi how are you', 'afternoon',
      'good day', 'howdy do', 'whats crackin', 'whats happening', 'ayy',
      'hey there friend', 'hi again', 'hello again',
    ],
  },
  'system.chit_chat.status': {
    examples: [
      'how are you', 'how are you doing', "how's it going", "what's up",
      'how is everything', 'sup', "what's happening", 'how are things',
      'are you there', 'you awake', 'how is it going', "how's life",
      "how's your day", 'you good', 'everything okay', 'what are you doing',
      'how do you feel', 'how is your day going', "how's tricks",
      "how's it hanging", 'you alive', 'still there', 'status report',
      'are you listening', 'how goes it', "how's everything going",
      'whats new', 'whats going on', 'how have you been',
      'how are you feeling today', 'you doing okay', 'all good',
      'how are you doing today', 'what are you up to',
    ],
  },
  'system.chit_chat.gratitude': {
    examples: [
      'thanks', 'thank you', 'thank you very much', 'awesome', 'great thanks',
      'appreciate it', 'much appreciated', 'thanks a lot', 'thanks so much',
      'cheers', 'thank you kindly', 'thanks a bunch', 'many thanks',
      'thanks a ton', 'that is great thanks', 'thanks friend',
      'thank you so much', 'much obliged', 'i appreciate that',
      'that is very helpful thanks', 'kudos', 'props to you',
      'you are the best', 'thank you very helpful', 'great job thanks',
      'nice one thanks', 'perfect thank you', 'good stuff thanks',
      'thanks for the help', 'appreciate the help', 'thank you kindly',
    ],
  },
  'system.chit_chat.clear': {
    examples: [
      'clear', 'clear console', 'clear chat', 'cls', 'clean screen', 'reset',
      'clear the screen', 'wipe the console', 'clear the chat',
      'clear everything', 'reset the console', 'clean up',
      'clear messages', 'wipe chat', 'clean the screen',
      'start fresh', 'clear this', 'reset chat', 'clear all',
      'clear window', 'wipe this clean', 'new screen',
    ],
  },
  'system.chit_chat.help': {
    examples: [
      'help', 'what can you do', 'list commands', 'show me what you can do',
      'how do i use this', 'commands list', 'available commands',
      'what commands', 'show commands', 'how does this work',
      'what are the commands', 'show available commands', 'help me',
      'i need help', 'what can i do', 'give me help',
      'help please', 'what are my options', 'show help',
      'what functionality do you have', 'what can you do for me',
      'how do i use you', 'what is available', 'list all commands',
      'show all commands', 'what features are there',
      'what are the available actions', 'commands help',
      'tutorial', 'how to use', 'guide me',
    ],
  },
  'system.chit_chat.git_status': {
    examples: [
      'git status', 'show changes', 'check git', 'what changed',
      'show me the git status', 'any changes', 'latest changes',
      'what changes have been made', 'what changed recently',
      'git diff', 'show git log', 'recent commits', 'commit history',
      'show me what changed', 'what is new', 'any uncommitted changes',
      'show git status', 'what files changed', 'git changes',
      'check git status', 'show recent commits', 'display git log',
      'list recent commits', 'uncommitted changes', 'unstaged changes',
      'what have i changed', 'git diff summary', 'modified files',
      'show modified files', 'git changes today',
      'what is the git status', 'show changes since last commit',
      'are there any changes', 'pending changes', 'git check',
    ],
  },
  'system.chit_chat.deploy': {
    examples: [
      'deploy', 'deploy the site', 'deploy this', 'deploy to production',
      'push live', 'ship it', 'push to git', 'push my changes',
      'commit and push', 'deploy to vercel', 'publish the site', 'go live',
      'push this live', 'deploy my changes', 'send it live', 'get this pushed',
      'commit my changes', 'push this to github', 'deploy the project',
      'deploy to server', 'push to github', 'ship this',
      'release the project', 'deploy everything', 'make it live',
      'publish to production', 'push to production', 'deploy my project',
      'send to production', 'upload to production', 'release this',
      'go to production', 'deploy to the server', 'ship to production',
      'push it', 'push these changes', 'deploy this to vercel',
      'deploy to hosting', 'launch the site', 'put this live',
    ],
  },
  'system.chit_chat.explain_followup': {
    examples: [
      'explain more', 'tell me more', 'elaborate', 'deep dive',
      'give me more details', 'go deeper', 'expand on that',
      'more info please', 'details please', 'explain further',
      'break it down further', 'give me the details', 'elaborate on that',
      'can you elaborate', 'tell me in detail', 'go into more detail',
      'explain in detail', 'i need more information', 'details',
      'more details', 'tell me everything', 'expand on this',
      'give me the full picture', 'break it down', 'explain thoroughly',
      'what else can you tell me', 'tell me more about that',
      'go into detail', 'expand', 'more information',
    ],
  },
  'system.chit_chat.undo': {
    examples: [
      'undo', 'undo last command', 'undo that', 'revert', 'go back',
      'rollback', 'undo the last change', 'revert last action',
      'undo my last action', 'cancel last change', 'take that back',
      'undo previous command', 'revert the last command',
      'undo this', 'undo what i just did', 'go back to before',
      'revert changes', 'undo the change', 'reverse last action',
      'cancel that', 'never mind undo', 'roll back the last change',
      'revert the last change', 'put it back', 'restore',
    ],
  },
  'system.chit_chat.yes_no': {
    examples: [
      'yes', 'yeah', 'yep', 'sure', 'do it', 'go ahead', 'confirm',
      'approve', 'yes please', 'yeah do it', 'sure go ahead',
      'okay', 'ok', 'fine', 'alright', 'yes go ahead',
      'please proceed', 'do it please', 'yep do it', 'affirmative',
      'thats right', 'correct', 'no', 'nope', 'nah', 'cancel',
      'do not do it', 'stop', 'abort', 'never mind', 'dont',
      'no thanks', 'not now', 'skip', 'decline', 'reject',
      'please no', 'no do not', 'negative', 'nope cancel',
    ],
  },
  'project.knowledge.overview': {
    examples: [
      'describe', 'info', 'what is this project', 'overview',
      'project overview', 'tell me about this project', 'give me an overview',
      'what does this do', 'describe the project', 'about this project',
      'project info', 'summary', 'what is this', 'tell me about it',
      'explain this project', 'what does this project do',
      'describe this project to me', 'brief me on this project',
      'project summary', 'what is the project about',
      'give me a summary', 'tell me about the project',
      'overview of this project', 'project description',
      'what is this thing', 'introduce this project',
      'what does this project involve', 'whats this all about',
    ],
  },
  'project.knowledge.stack': {
    examples: [
      'what is the stack', 'tech stack', 'what tech does it use',
      'technology stack', 'what technologies', 'what is this built with',
      'what framework', 'tech used', 'what tools does it use',
      'what languages are used', 'the tech stack',
      'what technologies are used here', 'how is this built',
      'what is the technology stack', 'tell me about the stack',
      'what frameworks', 'what tools', 'what is the architecture',
      'tech details', 'technology used', 'built with what',
      'show me the tech', 'what programming languages',
      'what is under the hood', 'what runs this',
      'what is the technical stack', 'what libraries',
    ],
  },
  'project.knowledge.commands': {
    examples: [
      'what are the commands', 'how do i run this', 'show me the commands',
      'what can i do with this', 'list commands for this project',
      'available actions', 'project commands', 'how to run the project',
      'what commands can i use', 'list available commands',
      'how do i use this project', 'how to use this',
      'what actions are there', 'list actions',
      'how do i work with this', 'tell me the commands',
      'what scripts are available', 'what can i run',
      'show project commands', 'commands for this project',
      'how to start', 'how to get started', 'run instructions',
    ],
  },
  'project.knowledge.gotchas': {
    examples: [
      'show gotchas', 'known issues', 'what are the gotchas',
      'known bugs', 'what should i watch out for', 'caveats',
      'things to be careful about', 'any known problems',
      'what are the known issues', 'gotchas', 'issues to note',
      'warnings', 'what should i know before working',
      'common pitfalls', 'things to avoid', 'tricky parts',
      'known limitations', 'current issues', 'outstanding bugs',
      'what problems exist', 'any gotchas', 'gotchas for this project',
      'warnings about this project', 'risks', 'potential issues',
    ],
  },
  'project.knowledge.architecture': {
    examples: [
      'architecture', 'how is it structured', 'show architecture',
      'how does the code work', 'code architecture', 'system design',
      'how are things organized', 'architectural overview',
      'explain the architecture', 'architecture diagram',
      'how does the app work', 'internal structure',
      'how is everything connected', 'component architecture',
      'code organization', 'software architecture',
      'how is the project laid out', 'technical architecture',
      'high level architecture', 'system architecture',
      'show me the architecture', 'architecture details',
    ],
  },
  'project.context.structure': {
    examples: [
      'show me the project structure', 'what are the directories',
      'list the folders', 'folder structure', 'directory tree',
      'how are files organized', 'show file structure', 'project layout',
      'show me around', 'explore the project', 'how is this organized',
      'show directory structure', 'list directories',
      'what folders exist', 'show me the folder layout',
      'file organization', 'directory listing', 'list folders',
      'show me the directory tree', 'project tree',
      'what is the folder structure', 'explore the codebase',
      'show me folders', 'list all directories', 'tree view',
    ],
  },
  'project.context.languages': {
    examples: [
      'what languages', 'what programming languages', 'what language is this',
      'which languages are used', 'programming languages',
      'languages in this project', 'what is this written in',
      'what languages does this use', 'coding languages',
      'languages used', 'what code languages', 'tell me the languages',
      'what is the code written in', 'what languages are in use',
      'language breakdown', 'language diversity', 'language list',
      'show languages', 'what programming languages are used',
      'what is this coded in', 'languages breakdown',
    ],
  },
  'project.context.file_count': {
    examples: [
      'how many files', 'project size', 'how big is this project',
      'file count', 'total files', 'how many files in the project',
      'count files', 'number of files', 'how many source files',
      'how many directories', 'total directories', 'project stats',
      'project statistics', 'how large is this', 'file statistics',
      'total lines of code', 'loc', 'lines of code',
      'how many lines', 'project metrics', 'size of project',
      'how much code', 'codebase size', 'repository size',
    ],
  },
  'project.context.entry_point': {
    examples: [
      'what is the entry point', 'where does the app start',
      'main file', 'entry point', 'start file', 'where do i start',
      'index file', 'main entry', 'what file runs first',
      'what is the main file', 'starting point',
      'how do i launch this', 'where is the main function',
      'what is the root file', 'where does execution begin',
      'startup file', 'launch file', 'primary entry',
      'what gets run first', 'main entry point',
      'which file is the entry', 'app start file',
    ],
  },
  'project.context.tech_preview': {
    examples: [
      'give me a summary', 'project summary', 'tl dr', 'summary',
      'what do i need to know', 'tech overview', 'technical preview',
      'show me the project', 'quick overview', 'what should I know',
      'quick summary', 'brief me', 'executive summary',
      'high level summary', 'quick look', 'at a glance',
      'whats the gist', 'bottom line', 'key points',
      'essential info', 'fast overview', 'tl;dr',
      'brief overview', 'condensed info', 'key things to know',
    ],
  },
  'project.context.tests': {
    examples: [
      'run tests', 'how do i test', 'test the code', 'run the tests',
      'testing framework', 'what tests are there', 'show tests',
      'test status', 'run test suite', 'are there tests',
      'how to run tests', 'test the project', 'run all tests',
      'execute tests', 'tell me about tests', 'test coverage',
      'what testing tools', 'how to test this', 'unit tests',
      'integration tests', 'test setup', 'testing approach',
      'is there test coverage', 'how is testing done',
      'show test files', 'list tests', 'where are the tests',
    ],
  },
  'project.context.dependencies': {
    examples: [
      'show dependencies', 'what packages', 'list dependencies',
      'what does this depend on', 'npm packages', 'requirements',
      'package list', 'dependent packages', 'what packages does it use',
      'show package dependencies', 'what are the dependencies',
      'list packages', 'npm dependencies', 'package requirements',
      'third party packages', 'external packages', 'what libraries',
      'what is imported', 'dependency list', 'what does this need',
      'show me the packages', 'what are the requirements',
      'external dependencies', 'software dependencies',
    ],
  },
  'project.context.config': {
    examples: [
      'show config', 'configuration files', 'config files',
      'what settings', 'environment config', 'env file', 'env',
      'project configuration', 'show configuration', 'config settings',
      'what config files exist', 'show env file', 'display config',
      'configuration details', 'setup files', 'show settings',
      'list config files', 'view configuration', 'config options',
      'what environment variables', 'show the env', 'read config',
      'environment setup', 'settings files', 'project settings',
    ],
  },
  'run_project': {
    examples: [
      'can you run the site', 'can you run the code',
      'launch the app', 'open the website', 'run the application',
      'start the server', 'run project', 'start the site',
      'launch project', 'open the project', 'run it', 'start it',
      'can you run it', 'run the app', 'open the site',
      'start the application', 'show me the site',
      'run this project', 'open the app', 'start the program',
      'execute the program', 'launch the program', 'run the program',
      'start the service', 'run the service', 'open the application',
    ],
  },
  'git_push': {
    examples: [
      'push to origin', 'push my code', 'upload to github', 'sync my changes',
      'deploy to git', 'send to remote', 'push this branch', 'git push my commits',
      'upload my changes', 'push changes to remote', 'submit to github',
      'push to master', 'sync to remote', 'update the remote repo',
      'deploy my changes to git', 'send this upstream', 'push to main',
      'upload to git', 'sync with github', 'push commits',
      'push this to origin', 'git push origin', 'push to the remote',
      'send my code to github', 'push my branch', 'git push current branch',
      'upload code to repository', 'push to upstream',
      'sync my local changes', 'push local commits', 'remote push',
      'push the code', 'push the branch', 'push all changes',
      'push these commits', 'send changes to remote',
      'push to the server', 'push to repo', 'git push to origin',
      'upload commits to github', 'sync to the cloud',
    ],
  },
  'git_commit': {
    examples: [
      'commit my changes', 'commit with message', 'save my work',
      'commit everything', 'create a commit', 'save my changes',
      'make a commit', 'commit my code', 'commit the changes',
      'save and commit', 'commit this', 'commit my work',
      'commit changes with message', 'do a commit', 'git commit',
      'record my changes', 'save my progress', 'commit all files',
      'make a save point', 'commit staged changes',
      'commit with a description', 'save to git', 'commit now',
      'take a snapshot', 'git commit changes', 'save my code',
      'create a git commit', 'commit project', 'commit current state',
    ],
  },
  'git_commit_push': {
    examples: [
      'commit and push', 'save and push', 'commit and upload',
      'commit then push', 'add commit push', 'git add commit push',
      'save and upload to github', 'commit and push to origin',
      'do a commit and push', 'commit and sync', 'save commit push',
      'commit everything and push', 'check in and push',
      'git commit and push', 'stage commit push', 'save and sync',
      'commit and send to remote', 'commit all and push',
      'make a commit and push', 'do the full git flow',
    ],
  },
  'git_remote_add': {
    examples: [
      'add the github link', 'attach the github link', 'add a remote',
      'set the remote url', 'add remote origin', 'connect this to github',
      'link this to a github repo', 'add my repo url', 'set the github link',
      'attach github', 'connect to github repo', 'add the github repo url',
      'set up the remote', 'point this at my github repo', 'add remote origin url',
      'attach my repository link', 'link to github', 'set remote origin',
      'can i attach the github link', 'add the repo link',
    ],
  },
  'git_add': {
    examples: [
      'stage changes', 'add files', 'git add', 'stage my changes',
      'add to staging', 'stage everything', 'add all files',
      'git add all', 'stage my files', 'add changes to git',
      'stage the changes', 'add to index', 'git add everything',
      'stage all changes', 'add files to git', 'prepare for commit',
      'stage all', 'add all changes', 'git add current directory',
      'track new files', 'add new files to git', 'stage all files',
    ],
  },
  'git_init': {
    examples: [
      'initialize git', 'init a repo', 'start git', 'create a git repo',
      'set up git', 'git init', 'initialize repository',
      'create repository', 'start a git repository',
      'init git repo', 'create a new repo', 'set up version control',
      'initialize version control', 'start tracking with git',
      'create git repository', 'initialize a git repo',
      'set up git tracking', 'make this a git project',
      'start git tracking', 'create new git repo',
    ],
  },
  'git_ignore_add': {
    examples: [
      'add to gitignore', 'add to git ignore', 'ignore a file',
      'gitignore this', 'add node_modules to gitignore',
      'add file to gitignore', 'add to ignore list',
      'ignore this file', 'make git ignore this',
      'add entry to gitignore', 'put in gitignore',
      'add to the ignore file', 'ignore this folder',
      'git ignore add', 'add something to gitignore',
      'exclude from git', 'stop tracking but keep file',
      'add .env to gitignore', 'ignore this directory',
      'dont track this file', 'make git ignore this file',
      'add to git ignore list', 'ignore file in git',
    ],
  },
  'git_rm_cached': {
    examples: [
      'remove from git', 'untrack file', 'stop tracking',
      'remove from git tracking', 'git rm cached', 'untrack this file',
      'remove from version control', 'stop tracking this file',
      'remove node_modules from git', 'untrack a file',
      'remove from git index', 'git remove tracking',
      'remove file from git', 'untrack this folder',
      'remove from source control', 'stop git tracking',
      'remove from repository', 'git stop tracking',
      'unstage a file', 'remove from staging',
      'take out of git', 'stop versioning this file',
      'remove this from git', 'untrack these files',
      'remove directory from git',
    ],
  },
  'npm_install': {
    examples: [
      'install dependencies', 'npm install', 'install packages',
      'install node modules', 'install all deps', 'npm i',
      'install project dependencies', 'get the packages',
      'download dependencies', 'install required packages',
      'fetch dependencies', 'install node packages',
      'set up dependencies', 'install npm packages',
      'run npm install', 'install all packages',
      'install the dependencies', 'get node modules',
      'install everything', 'do npm install',
      'install the packages', 'npm install project',
      'install modules', 'install a package',
      'add a package', 'add dependency',
    ],
  },
  'npm_build': {
    examples: [
      'build the project', 'npm run build', 'build it',
      'compile the code', 'build the app', 'npm build',
      'create a build', 'build for production', 'compile',
      'run build', 'build the application', 'do the build',
      'build the site', 'compile project', 'build everything',
      'generate build', 'npm run build the project',
      'build production', 'build the bundle', 'compile the app',
      'do a build', 'run the build script', 'build project',
      'make a production build', 'build process',
    ],
  },
  'npm_run': {
    examples: [
      'run a script', 'npm run', 'execute a script',
      'run the dev script', 'run the build script',
      'run npm script', 'execute npm script',
      'run a npm script', 'run the test script',
      'run start script', 'npm run start', 'npm run a command',
      'execute a npm command', 'run script from package',
      'run package script', 'trigger npm script',
      'npm run something', 'run a command from package.json',
      'run script', 'execute npm command', 'run npm command',
      'run dev', 'npm run dev', 'start the dev server',
      'launch the dev server', 'run the dev server', 'start developing',
      'run dev server', 'open dev server', 'start the live server',
      'start a live server', 'run the live site', 'launch the live site',
      'start dev mode', 'run in dev mode', 'start development server',
      'start the development server', 'start dev server',
    ],
  },
  'file_create': {
    examples: [
      'create a file', 'make a new file', 'create file',
      'new file', 'create a file called', 'generate a file',
      'make file', 'add a new file', 'create new file',
      'write a new file', 'create a document',
      'make a new document', 'generate new file',
      'create a file named', 'make a file with name',
      'add a file to the project', 'create a text file',
      'new document', 'create a markdown file',
      'create a config file', 'make a new file called',
      'generate a file named', 'write a file',
      'create a source file', 'add a new document',
    ],
  },
  'file_read': {
    examples: [
      'read file', 'read this file', 'show me the file', 'open file',
      'show me the contents of', 'what is in this file', "what's in the file",
      'display the file', 'view the file', 'cat this file', 'print the file',
      'show the contents of', 'read the contents of', 'open this file',
      'what does the file say', 'show me what is in', 'read me the file',
      'can you read this file', 'can you show me this file',
    ],
  },
  'file_append': {
    examples: [
      'append to file', 'add a line to the file', 'add this to the file',
      'add a line to', 'append this to the file', 'add to the end of the file',
      'append text to the file', 'add a note to the file',
      'add this line to', 'append a line to', 'add to the bottom of the file',
      'tack this onto the file', 'add this to the end of',
      'append content to', 'add another line to the file',
    ],
  },
  'file_delete': {
    examples: [
      'delete a file', 'remove a file', 'delete file',
      'delete this file', 'remove file', 'delete the file',
      'get rid of this file', 'remove this file',
      'trash this file', 'delete a file from the project',
      'remove a file from the project', 'erase this file',
      'delete that file', 'remove the file',
      'delete the file named', 'remove a file called',
      'get rid of file', 'wipe this file',
    ],
  },
  'project_scan': {
    examples: [
      'rescan project', 'reindex project', 'scan again',
      'refresh project index', 'rebuild index',
      'reindex this project', 'scan the project again',
      'reindex codebase', 'rescan the directory',
      'update the index', 'refresh the codebase index',
      'reindex the codebase', 'update project index',
      'rebuild the index', 'rescan this project',
      'reindex my project', 'fresh scan', 'reindex',
      'refresh index', 'scan the codebase again',
    ],
  },
  // Confirmed live 2026-07-29 (CLI chat): "change project" had no real intent of its own and was
  // winning on 'project_scan' by loose semantic similarity (shares "project" + a short imperative
  // shape), returning reindex advice that told CLI users to "restart the console" — misleading,
  // since switching projects has nothing to do with restarting. Real intent, separate from scan.
  'project_list': {
    examples: [
      'change project', 'switch project', 'switch projects',
      'switch to another project', 'change to a different project',
      'different project', 'select another project', 'select a different project',
      'choose a different project', 'list projects', 'show projects',
      'show me the projects', 'what projects are available',
      'what projects do you have', 'list all projects', 'available projects',
    ],
  },
  'git_log': {
    examples: [
      'show commit history', 'git log', 'view commits',
      'show recent commits', 'list commits', 'commit log',
      'git history', 'show git history', 'view git log',
      'list recent commits', 'show me the commits',
      'commit history please', 'show git commits',
      'display commit log', 'view commit history',
      'recent git activity', 'git commits list',
      'show all commits', 'git log history',
      'show last commits', 'recent commits list',
    ],
  },
  'git_branch': {
    examples: [
      'list branches', 'show branches', 'git branch',
      'what branch am i on', 'current branch', 'view branches',
      'show git branches', 'list all branches', 'git show branch',
      'what branch', 'check current branch', 'list git branches',
      'show all branches', 'display branches',
      'what is my current branch', 'branches list',
      'tell me the current branch', 'active branch',
    ],
  },
  'git_checkout': {
    examples: [
      'switch branch', 'checkout branch', 'git checkout',
      'change branch', 'switch to another branch',
      'checkout a branch', 'switch to branch',
      'change to a different branch', 'move to branch',
      'checkout different branch', 'switch git branch',
      'change my branch', 'checkout the branch',
      'switch to a branch', 'move to another branch',
    ],
  },
  'git_pull': {
    examples: [
      'git pull', 'pull from remote', 'pull latest',
      'fetch and merge', 'sync with remote', 'update from remote',
      'pull changes', 'fetch latest', 'get latest changes',
      'pull from origin', 'git fetch and merge',
      'pull the latest', 'update my branch', 'get updates',
      'pull remote changes', 'sync with origin',
      'fetch from remote', 'pull the changes',
      'get the latest code', 'update from git',
    ],
  },
  'system.monitoring.metrics': {
    examples: [
      'show metrics', 'view metrics', 'monitoring', 'monitor',
      'show stats', 'view stats', 'performance stats',
      'latency metrics', 'pipeline metrics', 'show monitoring',
      'system metrics', 'console stats', 'metrics dashboard',
      'show performance', 'how is the console performing',
      'response times', 'show response times', 'metrics report',
      'display metrics', 'check performance', 'health check',
    ],
  },
};
