// oosUtterances.js — synthetic out-of-scope (OOS) corpus (Step 6).
//
// ~200 utterances no trigger-mode intent should EVER claim, across everyday topics far from a
// dev-console's domain. Hand-written offline (no local model is installed on this machine —
// pulling one just to sample these would trade a 400MB-4.7GB download for lower-quality,
// harder-to-review output), then frozen here for review. This file IS the review surface:
// veto an entry by deleting its line.
//
// Intended use, in order:
//   1. MEASUREMENT — every entry routes through matchInput; an OOS input dispatching a real
//      builtin is an OOS false positive (baseline for the Step-8 table).
//   2. TRAINING — the `train` list (clear-OOS only) feeds the NLP.js classifier as a distinct
//      none-of-the-above class (see nlpSeedIntents.js). Fully local: node-nlp is pure JS, and
//      the Step-5 Ollama path is untouched, so OOS detection works with no model installed.
//   3. NEVER — the `boundary` list is measure-only. Near-console verbs ("run a marathon",
//      "push the door") that must stay matchable for real commands; training on them would
//      teach the classifier to swallow live intents.
//
// Deliberately NOT in server/intents/ (that would leak an OOS pseudo-intent into the command
// catalog, Ctrl+K deck, help text, and suggestion chips — verified in commandCatalog.js,
// which builds generated entries from INTENTS). Deliberately NOT in the held-out eval set
// (different population: synthetic OOS vs real user messages).
//
// Deliberately NOT NLP training data either (Step-6 negative result, 2026-09-11): training
// this corpus as a none-of-the-above class broke 2 battery rows while generalizing ~0% to
// unseen OOS paraphrases (memorization without generalization at 15/30/45/90/179 docs, with
// deterministic retrains). OOS is a measurement corpus (check-oos FP rate) plus pin/floor
// material — never classifier training data. Full numbers in the Step-6 commit message.

// Clear-OOS training set: no console action verb as the main verb, no file/quote bait.
export const OOS_TRAIN = [
  // cooking
  'what is a good recipe for chicken soup',
  'how long do i bake sourdough bread',
  'give me a vegan lasagna recipe',
  'what temperature for roast potatoes',
  'how do i make pancakes from scratch',
  'best marinade for grilled salmon',
  'how many cups of flour for a cake',
  'what can i cook with leftover rice',
  'is sourdough starter supposed to smell sour',
  'how do i poach an egg properly',
  'what spices go in chicken curry',
  'how long to boil pasta al dente',
  'give me a low salt dinner idea',
  'what is the difference between baking soda and powder',
  'how do i keep herbs fresh longer',
  'what goes well with mashed potatoes',
  'how do i sharpen a kitchen knife safely',
  'what is the best oil for frying',
  'how long does cooked chicken last in the fridge',
  'what can i substitute for eggs in baking',
  // health
  'what should i do about a sore throat',
  'is it normal to feel dizzy after standing up',
  'how much water should i drink daily',
  'what are the symptoms of the flu',
  'how do i treat a mild sunburn',
  'should i see a doctor for this headache',
  'what helps with lower back pain',
  'is coffee bad for blood pressure',
  'how many hours of sleep do adults need',
  'what foods are high in iron',
  'how do i stop a nosebleed',
  'are vitamins actually useful',
  'what causes muscle cramps at night',
  'how do i relieve eye strain',
  'is it safe to exercise with a cold',
  'what is a healthy resting heart rate',
  'how do i fall asleep faster at night',
  'what stretches help with neck stiffness',
  'should i drink protein shakes after workouts',
  'how do i deal with seasonal allergies',
  // legal
  'can my landlord raise the rent without notice',
  'how do i contest a parking ticket',
  'what are my rights if my flight is cancelled',
  'do i need a lawyer for small claims court',
  'how long is a patent valid',
  'what is the difference between a will and a trust',
  'can i get a refund for a cancelled concert',
  'how do i file a noise complaint',
  'is it legal to record a phone call here',
  'what should i do if someone hits my parked car',
  'how does jury duty selection work',
  'can an employer withhold my final paycheck',
  'what is tenant deposit protection',
  'how do i dispute a charge on my bill',
  'can i break a lease early for a new job',
  'what does a tenancy agreement cover',
  'how do i report a lost passport abroad',
  // entertainment
  'who won the football match last night',
  'what is the new blockbuster movie about',
  'who is the most famous actor right now',
  'did my team make the playoffs',
  'what song is number one this week',
  'when does the next season of that show come out',
  'who won the tennis final yesterday',
  'what are the best movies of the year',
  'is that celebrity still married',
  'what time does the match start on saturday',
  'who scored the winning goal',
  'what album just dropped',
  'are concert tickets still available downtown',
  'which actor plays that detective character',
  'what is the plot of that new series',
  'who is performing at the festival',
  'what channel is the game on tonight',
  'who got voted off the show last night',
  'is the new album worth listening to',
  // travel
  'what are cheap flights to lagos in december',
  'which hotel is best near the airport',
  'do i need a visa to visit ghana',
  'what is the best time to visit paris',
  'how much is a train ticket to ibadan',
  'what should i pack for a beach holiday',
  'is travel insurance worth it',
  'what is the baggage allowance for economy',
  'how do i find hostels in abuja',
  'what currency do they use in kenya',
  'is it safe to travel alone at night there',
  'what are good road trip stops between cities',
  'how early should i arrive for an international flight',
  'what is the check in time for most hotels',
  'can i bring food through airport security',
  'what is the best seat on a long flight',
  'how do i beat jet lag quickly',
  // trivia and homework
  'who was the first president of nigeria',
  'what is the capital of australia',
  'how many continents are there',
  'what year did the moon landing happen',
  'who wrote things fall apart',
  'what is photosynthesis in simple terms',
  'how do volcanoes erupt',
  'what is the largest ocean on earth',
  'who painted the mona lisa',
  'what causes rainbows to form',
  'how many planets are in the solar system',
  'what is the speed of light',
  'who discovered penicillin',
  'what are the three states of matter',
  'how old are the pyramids of giza',
  'what language do they speak in brazil',
  'what is the deepest part of the ocean',
  'how do bees make honey exactly',
  'why is the sky blue during the day',
  // relationships
  'how do i apologize to a friend properly',
  'what is a good anniversary gift idea',
  'how do i deal with a difficult neighbour',
  'what should i say in a wedding speech',
  'how do i make new friends as an adult',
  'is it rude to cancel plans last minute',
  'how do i congratulate someone on a new baby',
  'what is a thoughtful birthday message',
  'how do i handle disagreements calmly',
  'should i invite coworkers to my wedding',
  'how do i thank someone for their help',
  'what do i write in a sympathy card',
  'how do i remember birthdays reliably',
  'what is a good housewarming gift',
  // money advice
  'should i invest in stocks right now',
  'what is a good monthly savings rate',
  'how do i start an emergency fund',
  'is buying a house better than renting',
  'what is compound interest explained simply',
  'how do i make a monthly budget',
  'should i pay off debt or save first',
  'what is the safest way to save money',
  'how do retirement accounts work',
  'is cryptocurrency a good investment',
  'what should i look for in a bank account',
  'how do i improve my credit score',
  'how much should i tip at a restaurant',
  'what is inflation in plain words',
  // gaming
  'what is the best weapon in that shooter game',
  'how do i beat the final boss',
  'what are the patch notes for the new update',
  'which character should i main',
  'how do i rank up faster in competitive',
  'what is the current game meta',
  'are the servers down for maintenance',
  'how do i join a clan or guild',
  'what settings do pro players use',
  'is this game cross platform',
  'how do i unlock all the achievements',
  'what is the rarest skin in the game',
  'how do i change my username in game',
  'what does ping mean in online games',
  'how do i stream games to my friends',
  'what is a battle pass and is it worth it',
  'which console should i buy this year',
  // weather (no weather intent exists — chit-chat owns greetings, not forecasts)
  'will it rain tomorrow in lagos',
  'what is the weather like this weekend',
  'is there a storm coming this week',
  'how hot will it get in august',
  'should i carry an umbrella today',
  'what is the harmattan season like',
  'how cold does it get in jos in december',
  'what is the rainy season in lagos',
  // genuine junk observed in real fallback logs (reviewed true-OOS, not coverage gaps)
  'https://github.com/someone/some-repo',
  'asdfgh nonsense words here',
  'xyzzy frobnicate the wobble',
  'You wrote foo to where',
  'random thought of the day',
  'zzzqxk blorple',
  'lorem ipsum dolor sit amet',
  'test test is this thing on',
  'who let the dogs out originally',
  'what is my horoscope for today',
  'how do i fold a fitted sheet',
  'what is the best way to learn french',
  'how do i grow tomatoes on a balcony',
  'what is daylight saving time for',
];

// Boundary probes — MEASURE ONLY, never train. Each looks console-adjacent but states no
// console command; all must still reach fallback (or a genuinely correct intent), never OOS.
export const OOS_BOUNDARY = [
  'run a marathon next spring',
  'push the door open quietly',
  'commit to the fitness plan',
  'where is my phone right now',
  'open the pod bay doors please',
  'delete my browser history',
  'remind me what the meaning of life is',
  'note to self be happy today',
  'how do i cook pasta',
  'what time is the football match',
  'can you fly to the moon',
  'is there a doctor in the house',
  'play some music for me',
  'tell me a joke about lawyers',
  'what should i wear to the wedding',
  'book me a table for two tonight',
  'call mom and tell her i said hi',
  'order a pizza with extra cheese',
  'set an alarm for six in the morning',
];
