// project.knowledge.* intents — CLAUDE.md/README-derived Q&A (overview, stack, commands,
// gotchas, architecture) plus the README-driven "how do I run this" intent. Split out of
// intentsData.js (2026-07-30) — see chitChatIntents.js's header comment for why.
export const PROJECT_KNOWLEDGE_INTENTS = {
  'project.knowledge.overview': {
    examples: [
      'describe', 'info', 'what is this project', 'overview',
      'project overview', 'tell me about this project', 'give me an overview',
      'what does this do', 'describe the project', 'about this project',
      'project info', 'summary', 'what is this', 'tell me about it',
      'explain this project', 'what does this project do',
      'describe this project to me', 'brief me on this project',
      'project summary', 'what is the project about',
      'give me a summary', 'tell me about the project',
      'overview of this project', 'project description',
      'what is this thing', 'introduce this project',
      'what does this project involve', 'whats this all about',
      'can you explain this project', 'whats going on in this project',
      'walk me through this project', 'give me the lowdown on this project',
      'what am i looking at', 'whats the purpose of this project',
      'what problem does this solve', 'why does this project exist',
      'context on this project', 'background on this project',
    ],
  },
  'project.knowledge.stack': {
    examples: [
      'what is the stack', 'tech stack', 'what tech does it use',
      'technology stack', 'what technologies', 'what is this built with',
      'what framework', 'tech used', 'what tools does it use',
      'what languages are used', 'the tech stack',
      'what technologies are used here', 'how is this built',
      'what is the technology stack', 'tell me about the stack',
      'what frameworks', 'what tools', 'what is the architecture',
      'tech details', 'technology used', 'built with what',
      'show me the tech',
      'what is under the hood', 'what runs this',
      'what is the technical stack',
      'whats it built in', 'what runtime does it use', 'what does it run on',
      'give me the tech stack', 'stack breakdown', 'what powers this project',
      'what packages does it rely on', 'core technologies used',
      'main technologies', 'primary stack',
    ],
  },
  'project.knowledge.commands': {
    examples: [
      'what are the commands', 'show me the commands',
      'what can i do with this', 'list commands for this project',
      'available actions', 'project commands', 'how to run the project',
      'what commands can i use', 'list available commands',
      'how do i use this project', 'how to use this',
      'what actions are there', 'list actions',
      'how do i work with this', 'tell me the commands',
      'what scripts are available', 'what can i run',
      'show project commands', 'commands for this project',
      'how to start', 'how to get started', 'run instructions',
      'what can i trigger', 'list of things i can ask', 'commands available here',
      'what triggers are set up', 'show configured commands',
      'what shortcuts are there', 'available shortcuts',
    ],
  },
  'project.knowledge.gotchas': {
    examples: [
      'show gotchas', 'known issues', 'what are the gotchas',
      'known bugs', 'what should i watch out for', 'caveats',
      'things to be careful about', 'any known problems',
      'what are the known issues', 'gotchas', 'issues to note',
      'warnings', 'what should i know before working',
      'common pitfalls', 'things to avoid', 'tricky parts',
      'known limitations', 'current issues', 'outstanding bugs',
      'what problems exist', 'any gotchas', 'gotchas for this project',
      'warnings about this project', 'risks', 'potential issues',
      'anything i should be aware of', 'known problems with this project',
      'is there anything broken', 'known bugs to watch for',
      'pitfalls to avoid', 'sharp edges', 'quirks of this project',
      'what trips people up here',
    ],
  },
  'project.knowledge.architecture': {
    examples: [
      'architecture', 'how is it structured', 'show architecture',
      'how does the code work', 'code architecture', 'system design',
      'how are things organized', 'architectural overview',
      'explain the architecture', 'architecture diagram',
      'how does the app work', 'internal structure',
      'how is everything connected', 'component architecture',
      'code organization', 'software architecture',
      'how is the project laid out', 'technical architecture',
      'high level architecture', 'system architecture',
      'show me the architecture', 'architecture details',
      'how do the pieces fit together', 'how do the parts connect',
      'whats the design like', 'explain the design', 'design overview',
      'how is the backend structured', 'how is the frontend structured',
      'walk me through the architecture',
    ],
  },
  'project.knowledge.how_to_run': {
    // New intent (2026-07-30, requested directly): purely informational "how do I run/install/
    // set this up" — distinct from run_project (which actually executes a command). Its handler
    // checks the project's own README/CLAUDE.md for a documented command first (readmeRunParser.js)
    // before falling back to a detected-stack description, and never silently guesses without
    // saying where the answer came from. Phrasing here is deliberately question-shaped ("how do
    // I", "what's the", "steps to") rather than imperative ("run it", "start the server") so the
    // semantic matcher has a real shot at keeping this separate from run_project's more
    // command-shaped examples.
    examples: [
      'how do i run this', 'how do i run this project', 'how to run this',
      'how do i start this project', 'how do i get this running',
      'how do i get this project running', 'how do i install this',
      'how do i install this project', 'how do i set this up',
      'how do i set up this project', 'what is the setup process',
      'what are the setup instructions', 'what are the install instructions',
      'how do i build this', 'how do i build and run this',
      'steps to run this project', 'steps to install this project',
      'steps to set up this project', 'instructions for running this',
      'instructions for running this repo', 'instructions to run this project',
      'what is the getting started guide', 'is there a getting started guide',
      'getting started guide', 'quick start guide', 'quick start instructions',
      'how do i get started with this project', 'how do i get started here',
      'what do i need to run this', 'what do i need to do to run this',
      'what command do i run for this', 'what command runs this project',
      'what is the run command', 'what is the command to run this',
      'what is the command to start this', 'what command starts the server',
      'how is this project supposed to be run', 'how is this meant to be run',
      'does the readme say how to run this', 'check the readme for run instructions',
      'what does the readme say about running this', 'read the readme for setup steps',
      'look in the readme for how to run this', 'what does the documentation say about running this',
      'how do i launch this from the readme', 'according to the readme how do i run this',
      'how do you run this repository', 'how do you build this repository',
      'what is the proper way to run this', 'whats the correct way to start this',
      'how should i run this locally', 'how do i run this locally',
      'how do i run this on my machine', 'how do i get this working locally',
      'how do i run this go project', 'how do i run this rust project',
      'how do i run this java project', 'how do i run this ruby project',
      'how do i run this php project', 'how do i run this dotnet project',
      'how do i run this c# project', 'how do i set up this go project',
      'how do i set up this rust project', 'how do i set up this java project',
      'how do i set up this ruby project', 'how do i set up this php project',
      'what command do i run for this flask app', 'what command runs this django app',
      'how do i start this spring boot app', 'how do i start this rails app',
      'how do i start this laravel app', 'how do i start this express app',
      'what dependencies do i need before running this',
      'do i need to install anything before running this',
      'what do i need installed to run this project',
      'what tools do i need for this project', 'what is required to run this',
      'is there a setup script', 'is there an installation script',
      'how do i configure this project', 'how do i initialize this project',
      'what environment do i need for this', 'how do i prepare this project to run',
      'walk me through running this project', 'walk me through setting this up',
      'explain how to run this project', 'explain the setup process',
      'summarize how to run this project', 'summarize the install steps',
      'tell me how to run this', 'tell me how to set this up',
      'tell me the steps to get this running', 'give me the run instructions',
      'give me the setup instructions', 'give me the install steps',
    ],
  },
};
