// Phase 1.5 (UPGRADE-ROADMAP.md, 2026-08-11): the chat-side openers for the shared interactive
// tool panels. Each entry's `opensPanel` field is the wire-contract tag: when such an intent
// matches, builtinTools.js sends the server answer with an `openPanel` field on the same
// `answer` payload so the web client switches to that panel. The CLI deliberately ignores
// `openPanel` (Phase 1.5's permanent CLI/web capability gap) — the answer text stays self-
// sufficient, naming the chat equivalent the CLI user can type instead.
export const TOOL_PANEL_INTENTS = {
  'system.tools.open_calculator': {
    opensPanel: 'calculator',
    examples: [
      'open calculator', 'open the calculator', 'open tools', 'open the tools',
    ],
  },
  'system.tools.open_pdf_tools': {
    opensPanel: 'pdf-tools',
    examples: [
      'open pdf tools', 'open the pdf tools', 'open pdf tools panel',
    
      'pdf open tools',
      'open pdf tools asap :p',
      'tools yo open pdf',
      'please show pdf tools',
      'so tools open the pdf',
      'HI, SHOW THE PDF TOOL',
      'Can you show the pdf tools asat :)',
      'tols open hi, pdf please',
      'show the pdf tools',
      'COULD YOU DISPLAY PDF TOOLS',
      'tools open pdf um',
      'start the pdf tools!!',
      'hey show the pdf tools :)',
      'display the pdf toosl thanks',
      'please tools pdf please the open',
      'open pdf tools asap :)',
      'Please tools open pdf',
      'could you start the pdf tools',
      'launch the pdf tools',
      'pdf open so panl tools!',
      'UM STAART TOOLS PDF',
      'paneel hi, open pdf tools',
      'TOOLS PDF THE SHOW',
      'yo show the pdf tools',
      'open um pdf pnael tools',
      'HI, TOOLS OPEN PDF THE',
      'hey, open tools pdf'
      ],
  },
  'system.tools.open_reminders': {
    opensPanel: 'reminders',
    examples: [
      'open reminders', 'open the reminders', 'open reminders panel', 'open the reminders panel',
    
      'OPEN THE ERMINDERS PANEL',
      'START THE REMINDERS',
      'show reminders',
      'OPNE THE REMINDERS PLEASE 🙏',
      'launch reminedrs panel',
      'open wlerts panel',
      'start reminders',
      'um open the alerts panel',
      'START THE REMINDERS THANKS...',
      'start the reminders',
      'please oprn alarms',
      'hey, open alarms thanks',
      'hi, open the alerts panel',
      'hey, display the reminders apnel',
      'so start the reminders',
      'Open the alerts',
      'could you remindrs open the',
      'Can you start reminders',
      'Hey display the reminders',
      'the open mes remind!!',
      'please display the reminders apnel',
      'can you show reminders',
      'OPEN THE ALERTS',
      'COUULD YOU OPEN REMINDERS PANEL :)',
      'open panel alerts you could',
      'hi, open the alerts for me',
      'hey show the reminders',
      'so start reminders asap :p',
      'reminders the show quickly panel',
      'mes open hey, remind'
      ],
  },
  'system.tools.open_file_tools': {
    opensPanel: 'file-tools',
    examples: [
      'open file tools', 'open the file tools', 'open file tools panel',
    
      'open the file yools please',
      'tools ifle open',
      'display the file toools',
      'open ile tools panel :)',
      'can you open fine tools panel',
      'OPEN DOC TOOLS',
      'tools the start file',
      'can you start the file tools',
      'The open tools file um',
      'tools document open',
      'open document toolss',
      'display file tools pannel thanks...',
      'could you open doc tools',
      'Open the fille tools',
      'open document tools panel',
      'hey, open doc tools panel!',
      'TOOLS DOC THE OPEN',
      'hey open the file teols',
      'hi, open file tools quigkly',
      'open hi, tools file panel',
      'so launch the file tools',
      'show the filn tools',
      'display file tools pnel',
      'open the document bools please',
      'hey open doc tools',
      'file the tools ocen',
      'display file tools',
      'um launch fine tools thanks',
      'file the tools open so',
      'open file tools panel please :)'
      ],
  },
  'system.tools.open_notes': {
    opensPanel: 'notes',
    examples: [
      'open notes', 'open the notes', 'open notes panel',
    
      'show notes please 🙏',
      'so open jot downs panel',
      'THE THANKS HEY OPEN NOTES',
      'open jot doowns quickly',
      'plase view notes thanks',
      'open noxes',
      'SHOW THE NOTES ASAP!!',
      'hi, start notes asap!!',
      'PAEL NOTES OPEN HEY,',
      'ozen memos panel',
      'SHOW NOTES',
      'open the jot downs :)',
      'View notes now :)',
      'COULD YOU SHOW THE NOTES',
      'notes hey, start',
      'SO OPEN THE JOT DOQNS',
      'Could memos you open now panel',
      'open the jot downs quickly 🙏',
      'start notes',
      'show notes for me',
      'CAN YOU OPEN THE JOT DOWNS 🙏',
      'hi, open jot downs',
      'PLEASE DISPLAY NOTES',
      'show notes please',
      'the notes hey, start',
      'notes asap the view!!',
      'open jot downs please',
      'show the notes :)',
      'open asap nootes panel 🙏',
      'show notes quickly'
      ],
  },
  'system.tools.open_csv_tools': {
    opensPanel: 'csv-tools',
    examples: [
      'open spreadsheet', 'open the spreadsheet', 'open csv tools', 'open the csv tools',
    
      'could spreadsheet you open',
      'Cjuld you open csv tools 🙏',
      'hey, launch spreadsheet the!',
      'open csv tools quiclky :p',
      'hi, start the csv tools',
      'so view asap spreadsheet',
      'the so spreadshet display 🙏',
      'FOR OPEN HEY SPREADSHEET THE ME',
      'display the spreadsheet',
      'hey, display the spreadsheet now',
      'hey, launch the csv tools thanks'
      ],
  },
  'system.tools.open_clipboard': {
    opensPanel: 'clipboard',
    examples: [
      'open clipboard', 'open the clipboard', 'open clipboard panel',
    
      'can you display the clipboard...',
      'display clipbboard',
      'um start the clipboard thanks',
      'so show clipboard',
      'SO SHOW CLIPBOARD 🙏',
      'So display the clipboard',
      'so sshow the clipboard',
      'hi, clipboard the open :)',
      'Show clippboard',
      'Display cipboard',
      'COULD YOU DISPLAY THE CLIPBOARD PLEASE',
      'start the clipboard!',
      'yo display clipboard pnael',
      'DISPLAY CLIPBOARD',
      'cliboard asap open the',
      'the could you clipboard open',
      'you could open for me clipboard...',
      'clipboard thanks hi, open the',
      'Please sshow the clipboard',
      'hi, start the clipboard'
      ],
  },
  'system.tools.open_backup': {
    opensPanel: 'backup',
    examples: [
      'open backup', 'open backups', 'open the backup panel',
    
      'could you view backups for me!!',
      'um launch backups',
      'show backups!!',
      'display backwp',
      'show backup',
      'view backups please!',
      'could you show backup',
      'view the backup paenl',
      'please backup can you open',
      'hey view backup',
      'so start backups',
      'start backups',
      'DISPLAY BACKUPS',
      'BACKUP PLEAASE SHOW',
      'Start backups',
      'so view backups',
      'START BACKUP QUICKLY :P',
      'hey view backup!',
      'yo show backups quickly',
      'open backup quickly :p',
      'view backup',
      'PEN BACKUP',
      'please display the bacukp panel',
      'stait backup please',
      'the open bakcup panel',
      'Display backup now :p',
      'start backup quickly',
      'please display ackups for me :)'
      ],
  },
  'system.tools.open_notifications': {
    opensPanel: 'notifications',
    examples: [
      'open notifications', 'open the notifications', 'open notifications panel',
    ],
  },
  'system.tools.open_documents': {
    opensPanel: 'knowledge-base',
    examples: [
      'open documents', 'open the documents', 'open knowledge base', 'open document search',
    
      'OPEN ME YOU DOCUMENTS FOR COULD',
      'Start documents',
      'display docuemnts',
      'documents the open 🙏',
      'could you open documents thanks 🙏',
      'bvse knowledge so open :p',
      'base hi, knowledge open thanks',
      'Can you statr documents...',
      'launch documents 🙏',
      'the documents open',
      'display the documegts',
      'documents the open you can!!'
      ],
  },
  'system.tools.open_marketplace': {
    opensPanel: 'marketplace',
    examples: [
      'open marketplace', 'open the marketplace', 'open pack marketplace', 'open the pack store',
    ],
  },
  // Round-6 audit (2026-08-24): repo-map opener — the panel is the visual counterpart of the
  // whole-project map the AI prompt receives.
  'system.tools.open_repo_map': {
    opensPanel: 'repo-map',
    examples: [
      'open repo map', 'open the repo map', 'show the repo map', 'show me the repo map',
    
      'display me the repo map',
      'can you open repo map asbp',
      'repo the opmn map',
      'Repo please open the map',
      'open repo map quicckly',
      'you repo map can view the',
      'quickly hey, open map repo',
      'tpen map repo',
      'could repo you view the map',
      'repo asap map the oten',
      'could you show the repo map quickly :p',
      'OPPEN REPO MAP THANKS 🙏',
      'erpo the asap me map show',
      'Um what are the repo map',
      'UM REPO SHOW MAP THE!',
      'so launch repo map',
      'Map hey thanks repo open',
      'hhey, show me the repo map...',
      'hey dislay the repo map thanks',
      'map open the repo 🙏'
      ],
  },
  'system.tools.open_folder_explorer': {
    opensPanel: 'folder-explorer',
    examples: [
      'open folder explorer', 'open the folder explorer', 'open file explorer', 'open the file explorer',
      'browse a folder', 'browse folders', 'explore folders',
    
      'could you open the file explorek',
      'hey, open the file explorr',
      'CAN YOU START THE FILE EXPLORER',
      'open file explwrer',
      'open doc explorer asap',
      'please display folder explorer for me',
      'open the file expllorer',
      'brwose folders for me 🙏',
      'Show the folder explorer now',
      'start file explorer',
      'open the doc explorer asaap',
      'Heyo open document explorer',
      'folder explorer the show please',
      'OPN THE DOCUMENT EXPLORER',
      'heey, open folder explorer quickly',
      'open file explorer now :)',
      'display explorer folder 🙏',
      'open fodler explorer',
      'VIEW FILE EXPLORER',
      'oen file explorer quickly...',
      'yo open file exploorer quickly',
      'OPEN THE DOC EXPLOORER',
      'explorer file oppen',
      'Exlorer folder please open',
      'OPEEN FILE EXPLORER THANKS',
      'launch file explorer!',
      'hey, open explorer file',
      'hey quickly display the folder explorer'
      ],
  },
};